#!/usr/bin/env python3
"""Build the EXODUS PROTOCOL Parts Bible from the catalog.

Usage:
    python3 tools/parts/build.py            # regenerate docs, JSON and CSV
    python3 tools/parts/build.py --check    # validate only; exit 1 on problems

Outputs (all under docs/parts-bible/):
    data/parts.json            full registry incl. standards and expanded Blender assets
    data/components.json       components + resources
    data/equipment.json        handheld equipment, suits, modules, drones
    data/art_tracker_parts.csv one row per block asset (production tracker)
    data/art_tracker_props.csv one row per component/resource/equipment asset
    01-master-parts-list.md    every part in one list
    02..16-*.md                one chapter per category with a detail card per part
    17-components-and-resources.md
    18-handheld-equipment-and-suits.md
"""

import csv
import json
import re
import sys
from collections import Counter, OrderedDict
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
OUT = ROOT / "docs" / "parts-bible"
DATA = OUT / "data"

sys.path.insert(0, str(HERE))
from catalog import COMPONENTS, EQUIPMENT, PARTS, RESOURCES  # noqa: E402
from catalog import standards as S  # noqa: E402

FACE_ORDER = ["front", "back", "left", "right", "top", "bottom"]
KNOWN_SHAPES = {
    "box", "cube", "slope", "corner", "inv_corner", "half", "slope2_base", "slope2_tip",
    "corner2_base", "corner2_tip", "inv_corner2_base", "inv_corner2_tip", "round_slope",
    "round_corner", "round_inv_corner", "panel", "panel_slope", "panel_top", "flat", "wall",
    "floor", "cylinder",
}
SUBSCRIPTS = str.maketrans("₀₁₂₃₄₅₆₇₈₉", "0123456789")
GENERATED_NOTE = "<!-- GENERATED by tools/parts/build.py from tools/parts/catalog/. Do not edit by hand. -->"


# --------------------------------------------------------------------------- helpers
def pascal(text):
    text = text.translate(SUBSCRIPTS).replace("×", "x").replace("&", "And").replace("'", "").replace("’", "")
    parts = re.split(r"[^0-9A-Za-z]+", text)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def snake(text):
    text = text.translate(SUBSCRIPTS).replace("×", "x").replace("&", "and").replace("'", "").replace("’", "")
    return re.sub(r"[^0-9a-z]+", "_", text.lower()).strip("_")


def faces(spec):
    if spec in (None, "", "none"):
        return []
    if spec == "all":
        return list(FACE_ORDER)
    out = [f.strip() for f in spec.split(",") if f.strip()]
    return out


def parse_socket(spec):
    m = re.fullmatch(r"([a-z_0-9]+)@([a-z]+)(?:\*(\d+))?", spec)
    if not m:
        raise ValueError(f"Bad socket spec {spec!r}")
    return {"type": m.group(1), "face": m.group(2), "count": int(m.group(3) or 1)}


def fmt_num(v):
    if v is None:
        return "—"
    if isinstance(v, float) and not v.is_integer():
        return f"{v:,.2f}".rstrip("0").rstrip(".")
    return f"{int(v):,}"


def fmt_power(kw):
    if not kw:
        return "—"
    sign = "+" if kw > 0 else "−"
    a = abs(kw)
    if a >= 1000:
        return f"{sign}{fmt_num(a / 1000)} MW"
    return f"{sign}{fmt_num(a)} kW"


def fmt_size(size):
    w, h, d = size
    return f"{w}×{h}×{d}"


def dims_m(size, grid):
    c = S.CELL_M[grid]
    w, h, d = size
    return (round(w * c, 3), round(h * c, 3), round(d * c, 3))


def fmt_dims(dm):
    return " × ".join(f"{v:.2f}" for v in dm)


def lod_chain(tris0):
    return [max(S.LOD_MIN_TRIS, int(round(tris0 * r))) for r in S.LOD_RATIOS]


def debris_set(dm):
    m = max(dm)
    return "XS" if m < 1 else "S" if m < 3 else "M" if m < 8 else "L"


ITEM_NAMES = {c["id"]: c["name"] for c in COMPONENTS + RESOURCES}


def fmt_recipe(recipe):
    if not recipe:
        return "—"
    return ", ".join(f"{fmt_num(n)} {ITEM_NAMES.get(k, k)}" for k, n in recipe.items())


def scale_recipe(recipe, mult):
    if not recipe or mult == 1:
        return dict(recipe or {})
    return {k: max(1, int(round(v * mult))) for k, v in recipe.items()}


def md_escape(text):
    return text.replace("|", "\\|")


# --------------------------------------------------------------------------- expand
def expand():
    problems = []
    counters = Counter()
    parts = []
    seen_ids, seen_assets = set(), set()
    item_ids = set(ITEM_NAMES)

    for raw in PARTS:
        code = raw["code"]
        cat_key, cat_name, _doc = S.CATEGORIES[code]
        counters[code] += 1
        pid = f"{code}-{counters[code]:03d}"
        key = raw["key"] or snake(raw["name"])
        registry_id = f"block.{cat_key}.{key}"
        if registry_id in seen_ids:
            problems.append(f"Duplicate registry id {registry_id}")
        seen_ids.add(registry_id)

        if raw["cls"] not in S.COMPLEXITY:
            problems.append(f"{pid}: unknown complexity {raw['cls']}")
        if raw["art"] not in S.ART_SETS:
            problems.append(f"{pid}: unknown art set {raw['art']}")
        if raw["shape"] not in KNOWN_SHAPES:
            problems.append(f"{pid}: unknown shape {raw['shape']}")
        for spec_name in ("mounts", "airtight"):
            for f in faces(raw[spec_name]):
                if f not in FACE_ORDER:
                    problems.append(f"{pid}: bad face {f!r} in {spec_name}")
        sockets = []
        for spec in raw["sockets"]:
            try:
                s = parse_socket(spec)
            except ValueError as e:
                problems.append(f"{pid}: {e}")
                continue
            if s["type"] not in S.SOCKET_TYPES:
                problems.append(f"{pid}: unknown socket type {s['type']}")
            if s["face"] not in FACE_ORDER + ["center"]:
                problems.append(f"{pid}: unknown socket face {s['face']}")
            sockets.append(s)
        for grid, rec in raw["recipe"].items():
            for item in (rec or {}):
                if item not in item_ids:
                    problems.append(f"{pid}: recipe item {item!r} is not a known component/resource")

        cls = S.COMPLEXITY[raw["cls"]]
        stages = raw["stages"] or cls["stages"]
        variants = raw["variants"] or [None]
        assets = []
        for var in variants:
            vname = var["name"] if var else None
            grids = (var["grids"] if var and var["grids"] else raw["grids"])
            for grid, size in grids.items():
                base_mass = raw["mass"].get(grid) if raw["mass"] else None
                base_hp = raw["hp"].get(grid) if raw["hp"] else None
                mm = var["mass_mult"] if var else 1.0
                hm = var["hp_mult"] if var else 1.0
                mass = None if base_mass is None else int(round(base_mass * mm)) if base_mass * mm >= 10 else round(base_mass * mm, 1)
                hp = None if base_hp is None else int(round(base_hp * hm))
                if var and var["recipe"]:
                    recipe = var["recipe"].get(grid) or scale_recipe(raw["recipe"].get(grid), mm)
                else:
                    recipe = scale_recipe(raw["recipe"].get(grid), mm)
                for item in recipe:
                    if item not in item_ids:
                        problems.append(f"{pid}: variant recipe item {item!r} unknown")
                name = f"SM_{code}_{pascal(raw['name'])}" + (f"_{pascal(vname)}" if vname else "") + f"_{grid}"
                if name in seen_assets:
                    problems.append(f"Duplicate asset name {name}")
                seen_assets.add(name)
                dm = dims_m(size, grid)
                tris0 = cls["tris"][grid]
                assets.append(OrderedDict(
                    asset=name,
                    variant=vname,
                    grid=grid,
                    size_cells=list(size),
                    dims_m=list(dm),
                    tier=(var["tier"] if var and var["tier"] else raw["tier"]),
                    mass_kg=mass,
                    hp=hp,
                    power_kw=raw["power"].get(grid) if raw["power"] else None,
                    recipe=recipe,
                    shape=(var["shape"] if var and var["shape"] else raw["shape"]),
                    lod_tris=lod_chain(tris0),
                    debris_set=debris_set(dm),
                    texel_density_px_per_m=S.TEXEL_DENSITY[grid],
                    blend_path=f"assets/parts/{cat_key}/{name}.blend",
                    export_path=f"export/parts/{cat_key}/{name}.fbx",
                    variant_notes=(var["notes"] if var else ""),
                ))

        parts.append(OrderedDict(
            id=pid,
            registry_id=registry_id,
            name=raw["name"],
            category=code,
            category_name=cat_name,
            sub=raw["sub"],
            tier=raw["tier"],
            art_set=raw["art"],
            complexity=raw["cls"],
            function=raw["function"],
            unlock=raw["unlock"],
            grids={g: list(s) for g, s in raw["grids"].items()},
            stats=raw["stats"],
            mount_faces=faces(raw["mounts"]),
            airtight_faces=faces(raw["airtight"]),
            sockets=sockets,
            moving_parts=raw["moving"],
            emissive=raw["emissive"],
            vfx=raw["vfx"],
            audio=raw["audio"],
            build_stages=stages,
            collision_max_hulls=cls["collision"],
            modeling_notes=raw["notes"],
            assets=assets,
        ))
    return parts, problems


def socket_names(sockets):
    out = []
    for s in sockets:
        for i in range(1, s["count"] + 1):
            out.append(f"SOCKET_{pascal(s['type'])}_{pascal(s['face'])}_{i:02d}")
    return out


# --------------------------------------------------------------------------- markdown
def part_card(p):
    cls = S.COMPLEXITY[p["complexity"]]
    art = S.ART_SETS[p["art_set"]]
    grids = list(p["grids"])
    base_assets = {}
    for a in p["assets"]:
        base_assets.setdefault(a["grid"], a)

    lines = [f"### {p['id']} · {p['name']}", ""]
    lines.append(f"`{p['registry_id']}` · **Tier** {p['tier']} · **Art set** {art['name']} · "
                 f"**Complexity** {p['complexity']} ({cls['label']}) · **Group** {p['sub']}")
    lines.append("")
    lines.append(f"> {p['function']}")
    lines.append("")

    # Gameplay table
    head = "| | " + " | ".join(S.GRID_NAMES[g] for g in grids) + " |"
    lines += ["**Gameplay (base variant)**", "", head, "|---|" + "---|" * len(grids)]

    def row(label, fn):
        lines.append(f"| {label} | " + " | ".join(fn(base_assets[g]) for g in grids) + " |")

    row("Size (cells, W×H×D)", lambda a: fmt_size(a["size_cells"]))
    row("Dimensions (m, W×H×D)", lambda a: fmt_dims(a["dims_m"]))
    row("Mass", lambda a: f"{fmt_num(a['mass_kg'])} kg" if a["mass_kg"] is not None else "—")
    row("Integrity (HP)", lambda a: fmt_num(a["hp"]))
    row("Power", lambda a: fmt_power(a["power_kw"]))
    row("Recipe", lambda a: md_escape(fmt_recipe(a["recipe"])))
    lines.append("")
    extras = []
    for k, v in p["stats"].items():
        if isinstance(v, dict):
            v = " / ".join(f"{g} {fmt_num(x) if isinstance(x, (int, float)) else x}" for g, x in v.items())
        extras.append(f"{k.replace('_', ' ')}: {v}")
    if extras:
        lines.append("**Stats:** " + md_escape(" · ".join(str(e) for e in extras)))
        lines.append("")
    if p["unlock"]:
        lines.append(f"**Unlock:** {p['unlock']}")
        lines.append("")

    # Asset table
    lines += ["**Blender assets**", "",
              "| Asset | Variant | Grid | Dimensions (m) | Tier | Mass (kg) | HP | Tris LOD0 / 1 / 2 / 3 | Debris |",
              "|---|---|---|---|---|---|---|---|---|"]
    for a in p["assets"]:
        lines.append(f"| `{a['asset']}` | {a['variant'] or '—'} | {a['grid']} | {fmt_dims(a['dims_m'])} | {a['tier']} | "
                     f"{fmt_num(a['mass_kg'])} | {fmt_num(a['hp'])} | {' / '.join(fmt_num(t) for t in a['lod_tris'])} | {a['debris_set']} |")
    lines.append("")

    # Blender detail
    mounts = ", ".join(p["mount_faces"]) if p["mount_faces"] else "none (sub-grid or free-standing)"
    if len(p["mount_faces"]) == 6:
        mounts = "all six faces"
    air = ", ".join(p["airtight_faces"]) if p["airtight_faces"] else "none"
    if len(p["airtight_faces"]) == 6:
        air = "all six faces"
    stage_names = S.BUILD_STAGE_NAMES.get(p["build_stages"], [])
    lines += ["**Blender detail**", ""]
    lines.append("- **Pivot & axes:** origin at the bounding-volume center, grid-aligned. Front = +X, up = +Z, left = +Y. Apply all transforms (scale 1.0).")
    lines.append(f"- **Mount faces:** {mounts} · **Airtight faces:** {air}")
    lines.append(f"- **Construction stages:** {p['build_stages']} — " + ", ".join(stage_names) + " (`<asset>_BS1…`), plus the final mesh")
    lines.append(f"- **Collision:** ≤ {p['collision_max_hulls']} convex hulls named `UCX_<asset>_NN`")
    lines.append(f"- **Materials:** `{art['materials']}` ({art['name']}) · {cls['texture']} · texel density "
                 f"{fmt_num(S.TEXEL_DENSITY['LG'])} px/m (LG) / {fmt_num(S.TEXEL_DENSITY['SG'])} px/m (SG) · damage overlay + deformation mask")
    socks = socket_names(p["sockets"])
    if socks:
        lines.append("- **Sockets (empties):** " + ", ".join(f"`{s}`" for s in socks))
    else:
        lines.append("- **Sockets (empties):** none")
    if p["moving_parts"]:
        lines.append("- **Moving parts (`PART_*` pivots):** " + md_escape("; ".join(p["moving_parts"])))
    if p["emissive"]:
        lines.append("- **Emissive:** " + md_escape("; ".join(p["emissive"])))
    if p["vfx"]:
        lines.append("- **VFX:** " + md_escape("; ".join(p["vfx"])))
    if p["audio"]:
        lines.append("- **Audio:** " + md_escape("; ".join(p["audio"])))
    if p["modeling_notes"]:
        lines.append("- **Modeling notes:** " + md_escape(p["modeling_notes"]))
    vnotes = [(a["variant"], a["variant_notes"]) for a in p["assets"] if a["variant_notes"]]
    seen = set()
    for vn, note in vnotes:
        if vn in seen:
            continue
        seen.add(vn)
        lines.append(f"- **{vn} variant:** {md_escape(note)}")
    lines.append(f"- **Files:** `{p['assets'][0]['blend_path'].rsplit('/', 1)[0]}/<asset>.blend` → `export/parts/…/<asset>.fbx`")
    lines.append("")
    return "\n".join(lines)


def category_doc(code, parts):
    cat_key, cat_name, doc = S.CATEGORIES[code]
    number = doc.split("-", 1)[0]
    cps = [p for p in parts if p["category"] == code]
    n_assets = sum(len(p["assets"]) for p in cps)
    out = [GENERATED_NOTE, f"# {number} — {cat_name}", "",
           S.CATEGORY_INTROS[code], "",
           f"**{len(cps)} parts · {n_assets} Blender assets.** Standards for every card are in "
           f"[00 — Blender Modeling Standards](00-blender-modeling-standards.md).", ""]
    image = OUT / "images" / f"{cat_key}-blockouts.jpg"
    if image.exists():
        out += [f"![{cat_name} blockout shapes generated by the Blender toolkit](images/{image.name})", "",
                "*Blockouts generated by `tools/blender/exodus_parts.py` at exact grid size (large grid, 2.5 m cells).*", ""]
    out += ["## Contents", "",
           "| ID | Part | Group | Grids | Tier | Assets |", "|---|---|---|---|---|---|"]
    for p in cps:
        anchor = re.sub(r"[^a-z0-9 -]", "", f"{p['id']} · {p['name']}".lower()).replace(" ", "-")
        out.append(f"| {p['id']} | [{p['name']}](#{anchor}) | {p['sub']} | {' · '.join(p['grids'])} | {p['tier']} | {len(p['assets'])} |")
    out += ["", "---", ""]
    for p in cps:
        out.append(part_card(p))
        out.append("---")
        out.append("")
    return "\n".join(out)


def master_doc(parts):
    total_assets = sum(len(p["assets"]) for p in parts)
    out = [GENERATED_NOTE, "# 01 — Master Parts List", "",
           f"Every buildable part in EXODUS PROTOCOL: **{len(parts)} parts** producing **{total_assets} Blender assets** "
           "(one per grid size and variant). Click a category for full detail cards.", "",
           "## Summary by category", "",
           "| Code | Category | Parts | Blender assets | Chapter |", "|---|---|---|---|---|"]
    for code, (_k, name, doc) in S.CATEGORIES.items():
        cps = [p for p in parts if p["category"] == code]
        out.append(f"| {code} | {name} | {len(cps)} | {sum(len(p['assets']) for p in cps)} | [{doc}]({doc}) |")
    out.append(f"| | **Total** | **{len(parts)}** | **{total_assets}** | |")
    out.append("")

    tiers = Counter(p["tier"] for p in parts)
    out += ["## Parts by tier", "", "| Tier | Parts |", "|---|---|"]
    for t in sorted(tiers):
        out.append(f"| {t} | {tiers[t]} |")
    out.append("")

    for code, (_k, name, doc) in S.CATEGORIES.items():
        out += [f"## {code} — {name}", "",
                "| ID | Part | Group | LG size | SG size | Tier | Art set | Variants | Registry ID |",
                "|---|---|---|---|---|---|---|---|---|"]
        for p in (x for x in parts if x["category"] == code):
            lg = fmt_size(p["grids"]["LG"]) if "LG" in p["grids"] else "—"
            sg = fmt_size(p["grids"]["SG"]) if "SG" in p["grids"] else "—"
            variants = sorted({a["variant"] for a in p["assets"] if a["variant"]}, key=lambda v: [a["variant"] for a in p["assets"]].index(v))
            out.append(f"| {p['id']} | {p['name']} | {p['sub']} | {lg} | {sg} | {p['tier']} | {S.ART_SETS[p['art_set']]['name']} | "
                       f"{', '.join(variants) if variants else '—'} | `{p['registry_id']}` |")
        out.append("")
    return "\n".join(out)


def components_doc(parts):
    usage = Counter()
    for p in parts:
        used = set()
        for a in p["assets"]:
            used.update(a["recipe"])
        for item in used:
            usage[item] += 1
    ingredients_use = Counter()
    for c in COMPONENTS + RESOURCES:
        for k in c["ingredients"]:
            ingredients_use[k] += 1

    def table(items, prefix):
        rows = ["| Asset | Item | Tier | Source / made at | Ingredients | Used by parts | Prop size (m) | LOD0 tris | Look |",
                "|---|---|---|---|---|---|---|---|---|"]
        for c in items:
            ing = ", ".join(f"{fmt_num(v)} {ITEM_NAMES.get(k, k)}" for k, v in c["ingredients"].items()) or "—"
            used = usage.get(c["id"], 0)
            if not used and ingredients_use.get(c["id"]):
                used_txt = f"ingredient ×{ingredients_use[c['id']]}"
            else:
                used_txt = str(used) if used else "—"
            rows.append(f"| `{prefix}_{pascal(c['name'])}` | **{c['name']}** (`{c['id']}`) | {c['tier']} | {c['made_at']} | "
                        f"{md_escape(ing)} | {used_txt} | {fmt_dims(c['dims_m'])} | {fmt_num(c['tris'])} | {md_escape(c['look'])} |")
        return rows

    out = [GENERATED_NOTE, "# 17 — Components & Resources", "",
           "Every crafting component and raw resource is also a small 3D prop: it shows up as loot, in inventory icon renders, "
           "floating in zero-G, and piled on construction-stage frames. Prop rules: pivot at the base center, one 512² texture "
           "(or a slot in the shared prop atlas), LOD1 at 50%, collision is one box or convex hull (`UCX_`).", "",
           "## Components", ""]
    out += table(COMPONENTS, "SM_CMP")
    out += ["", "## Resources, ingots & fuels", ""]
    out += table(RESOURCES, "SM_RES")
    out += ["", "## Construction-stage piles", "",
            "Frames at BS1/BS2 show component piles instead of empty scaffolds. Each component has a `SM_CMP_<Name>_Pile` "
            "variant (3–5 stacked units, ≤ 600 tris) that the construction system scatters on the frame's floor.", ""]
    return "\n".join(out)


def equipment_doc():
    out = [GENERATED_NOTE, "# 18 — Handheld Equipment, Suits & Drones", "",
           "First-person (1P) viewmodels are skeletal meshes on the shared weapon skeleton (`SK_EQP_<Name>_1P`); "
           "third-person (3P) world models (`SM_EQP_<Name>_3P`) are used on characters, as loot and on weapon racks. "
           "Suits are skeletal meshes on the character skeleton (`SK_SUIT_<Name>`). Texel density: 1P 2,048 px/m, 3P 1,024 px/m.", "",
           "**1P rules:** the grip socket sits at the palm center; the ADS sight socket is on the optical axis; animated parts are bones, not separate meshes; "
           "the muzzle socket's +X points down the barrel. **3P rules:** single mesh, max 2 materials, pivot at the grip.", ""]
    kinds = OrderedDict()
    for e in EQUIPMENT:
        kinds.setdefault(e["kind"], []).append(e)
    out += ["## Contents", "", "| Group | Items |", "|---|---|"]
    for k, items in kinds.items():
        out.append(f"| {k} | " + ", ".join(i["name"] for i in items) + " |")
    out.append("")
    for kind, items in kinds.items():
        out += [f"## {kind}", ""]
        for e in items:
            if e["kind"] == "Suit":
                assets = [f"SK_SUIT_{pascal(e['name'])}"]
            elif e["kind"] in ("Suit Module", "Drone"):
                assets = [f"SK_EQP_{pascal(e['name'])}" if e["bones"] else f"SM_EQP_{pascal(e['name'])}"]
            else:
                assets = [f"SK_EQP_{pascal(e['name'])}_1P", f"SM_EQP_{pascal(e['name'])}_3P"]
            out.append(f"### {e['name']}")
            out.append("")
            out.append(f"`item.{snake(e['kind'])}.{e['id']}` · **Tier** {e['tier']} · **Art set** {S.ART_SETS[e['art']]['name']} · "
                       f"**Assets** " + ", ".join(f"`{a}`" for a in assets))
            out.append("")
            if e["stats"]:
                out.append("**Stats:** " + md_escape(" · ".join(f"{k.replace('_', ' ')}: {v}" for k, v in e["stats"].items())))
                out.append("")
            budget = []
            if e["tris_1p"]:
                budget.append(f"1P {fmt_num(e['tris_1p'])} tris")
            if e["tris_3p"]:
                budget.append(f"3P {fmt_num(e['tris_3p'])} tris (LOD1 50%, LOD2 20%)")
            out.append(f"- **Size (m, L×H×W):** {fmt_dims(e['dims_m'])} · **Budget:** {', '.join(budget)} · **Textures:** {e['tex']}")
            if e["bones"]:
                out.append("- **Bones:** " + ", ".join(f"`{b}`" for b in e["bones"]))
            if e["sockets"]:
                out.append("- **Sockets:** " + ", ".join(e["sockets"]))
            if e["moving"]:
                out.append("- **Moving parts:** " + md_escape("; ".join(e["moving"])))
            if e["emissive"]:
                out.append("- **Emissive:** " + md_escape("; ".join(e["emissive"])))
            if e["vfx"]:
                out.append("- **VFX:** " + md_escape("; ".join(e["vfx"])))
            if e["notes"]:
                out.append("- **Notes:** " + md_escape(e["notes"]))
            out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------- csv / json
def write_csvs(parts):
    DATA.mkdir(parents=True, exist_ok=True)
    cols = ["asset", "part_id", "registry_id", "part_name", "variant", "category", "group", "grid", "size_cells_WxHxD",
            "dims_m_WxHxD", "tier", "art_set", "complexity", "mass_kg", "hp", "power_kw", "recipe",
            "lod0_tris", "lod1_tris", "lod2_tris", "lod3_tris", "build_stages", "collision_max_hulls",
            "texture_strategy", "texel_density_px_m", "mount_faces", "airtight_faces", "sockets", "moving_parts",
            "emissive", "debris_set", "blend_path", "export_path", "status", "owner", "notes"]
    with open(DATA / "art_tracker_parts.csv", "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(cols)
        for p in parts:
            for a in p["assets"]:
                w.writerow([
                    a["asset"], p["id"], p["registry_id"], p["name"], a["variant"] or "", p["category"], p["sub"], a["grid"],
                    fmt_size(a["size_cells"]), "x".join(f"{v:.2f}" for v in a["dims_m"]), a["tier"], p["art_set"],
                    p["complexity"], a["mass_kg"], a["hp"], a["power_kw"] or 0,
                    "; ".join(f"{k}:{v}" for k, v in a["recipe"].items()),
                    *a["lod_tris"], p["build_stages"], p["collision_max_hulls"],
                    S.COMPLEXITY[p["complexity"]]["texture"], a["texel_density_px_per_m"],
                    " ".join(p["mount_faces"]), " ".join(p["airtight_faces"]),
                    " ".join(socket_names(p["sockets"])), " | ".join(p["moving_parts"]),
                    " | ".join(p["emissive"]), a["debris_set"], a["blend_path"], a["export_path"],
                    "Not started", "", p["modeling_notes"],
                ])
    with open(DATA / "art_tracker_props.csv", "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["asset", "item_id", "name", "type", "tier", "dims_m", "tris_lod0_or_1p", "tris_3p", "textures", "status", "owner", "notes"])
        for c in COMPONENTS:
            w.writerow([f"SM_CMP_{pascal(c['name'])}", c["id"], c["name"], "Component", c["tier"],
                        "x".join(f"{v:.2f}" for v in c["dims_m"]), c["tris"], "", "512 / prop atlas", "Not started", "", c["look"]])
        for c in RESOURCES:
            w.writerow([f"SM_RES_{pascal(c['name'])}", c["id"], c["name"], c["kind"].title(), c["tier"],
                        "x".join(f"{v:.2f}" for v in c["dims_m"]), c["tris"], "", "512 / prop atlas", "Not started", "", c["look"]])
        for e in EQUIPMENT:
            if e["kind"] == "Suit":
                name = f"SK_SUIT_{pascal(e['name'])}"
            elif e["kind"] in ("Suit Module", "Drone"):
                name = f"SK_EQP_{pascal(e['name'])}" if e["bones"] else f"SM_EQP_{pascal(e['name'])}"
            else:
                name = f"SK_EQP_{pascal(e['name'])}_1P + SM_EQP_{pascal(e['name'])}_3P"
            w.writerow([name, e["id"], e["name"], e["kind"], e["tier"], "x".join(f"{v:.2f}" for v in e["dims_m"]),
                        e["tris_1p"] or "", e["tris_3p"] or "", e["tex"], "Not started", "", e["notes"]])


def write_json(parts):
    DATA.mkdir(parents=True, exist_ok=True)
    standards = {
        "cell_m": S.CELL_M,
        "texel_density_px_per_m": S.TEXEL_DENSITY,
        "complexity": S.COMPLEXITY,
        "lod_ratios": S.LOD_RATIOS,
        "lod_screen_size": S.LOD_SCREEN_SIZE,
        "lod_min_tris": S.LOD_MIN_TRIS,
        "build_stage_names": {str(k): v for k, v in S.BUILD_STAGE_NAMES.items()},
        "art_sets": S.ART_SETS,
        "faces": S.FACES,
        "socket_types": S.SOCKET_TYPES,
        "categories": {k: {"key": v[0], "name": v[1], "doc": v[2]} for k, v in S.CATEGORIES.items()},
        "axes": {"front": "+X", "up": "+Z", "left": "+Y", "units": "metres, unit scale 1.0"},
    }
    payload = OrderedDict(schema="exodus.parts/1", standards=standards, parts=parts)
    (DATA / "parts.json").write_text(json.dumps(payload, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    (DATA / "components.json").write_text(json.dumps(
        {"schema": "exodus.items/1", "components": COMPONENTS, "resources": RESOURCES}, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    (DATA / "equipment.json").write_text(json.dumps(
        {"schema": "exodus.equipment/1", "equipment": EQUIPMENT}, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")


def update_readme_stats(parts):
    readme = OUT / "README.md"
    if not readme.exists():
        return
    text = readme.read_text(encoding="utf-8")
    start, end = "<!-- STATS:START -->", "<!-- STATS:END -->"
    if start not in text or end not in text:
        return
    total_assets = sum(len(p["assets"]) for p in parts)
    lg = sum(1 for p in parts for a in p["assets"] if a["grid"] == "LG")
    sg = total_assets - lg
    n_equip_assets = sum(2 if e["kind"] not in ("Suit", "Suit Module", "Drone") else 1 for e in EQUIPMENT)
    stats = "\n".join([
        start,
        "| | Count |",
        "|---|---|",
        f"| Buildable parts | **{len(parts)}** across {len(S.CATEGORIES)} categories |",
        f"| Block assets (per grid × variant) | **{total_assets}** ({lg} large grid, {sg} small grid) |",
        f"| Components | {len(COMPONENTS)} |",
        f"| Resources, ingots & fuels | {len(RESOURCES)} |",
        f"| Handheld equipment, suits, modules & drones | {len(EQUIPMENT)} items ({n_equip_assets} assets) |",
        f"| **Total Blender assets** | **{total_assets + len(COMPONENTS) + len(RESOURCES) + n_equip_assets}** |",
        end,
    ])
    text = text[: text.index(start)] + stats + text[text.index(end) + len(end):]
    readme.write_text(text, encoding="utf-8")


def main():
    parts, problems = expand()
    if problems:
        print("Catalog problems:")
        for p in problems:
            print("  -", p)
        sys.exit(1)
    if "--check" in sys.argv:
        print(f"OK: {len(parts)} parts, {sum(len(p['assets']) for p in parts)} assets")
        return
    OUT.mkdir(parents=True, exist_ok=True)
    write_json(parts)
    write_csvs(parts)
    (OUT / "01-master-parts-list.md").write_text(master_doc(parts) + "\n", encoding="utf-8")
    for code, (_k, _n, doc) in S.CATEGORIES.items():
        (OUT / doc).write_text(category_doc(code, parts) + "\n", encoding="utf-8")
    (OUT / "17-components-and-resources.md").write_text(components_doc(parts) + "\n", encoding="utf-8")
    (OUT / "18-handheld-equipment-and-suits.md").write_text(equipment_doc() + "\n", encoding="utf-8")
    update_readme_stats(parts)
    total = sum(len(p["assets"]) for p in parts)
    print(f"Built {len(parts)} parts / {total} block assets, {len(COMPONENTS)} components, "
          f"{len(RESOURCES)} resources, {len(EQUIPMENT)} equipment items -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
