"""PLY — the player character; CST — the story cast (companions, antagonists, story NPCs)."""

from . import CH, H, O

# ---------------------------------------------------------------------------
# PLY — Wrench
# ---------------------------------------------------------------------------
CH("PLY", "Wrench (Ren Okafor)", key="wrench", title="The Engineer", tier="Hero", skeleton=H(1.78, "adult_athletic"),
   age="Early 30s", pronouns="Player-chosen (docs use they/them)", arms_1p=True, facial_capture=True,
   role="The player. A Kestrel systems engineer who, three years ago, operated the Persephone sample arm. Everyone calls them 'Wrench'.",
   appears="Entire game (first person; third person optional; in-engine scenes and cinematics)",
   story={"want": "Get the people in front of them to safety.",
          "need": "To accept responsibility for what they helped start without drowning in it.",
          "wound": "Raised by Ada after their mother died; Ada chose her career over them once before.",
          "lie": "\"I just fix machines. The big decisions belong to someone else.\"",
          "arc": "Protect (Act I) → lead (Act II) → grieve and choose (Act III) → decide for a species (Act IV)."},
   voice="Three voice sets (A/B/C), each recorded opposite the same Ada. Warm, dry, practical; humor under pressure.",
   visual={"silhouette": "Practical, compact and grounded: tool belt, rolled sleeves, wrist pad. Reads as 'the one who fixes things' at 30 m.",
           "face": "Default preset: warm brown skin, strong brows, tired but kind eyes, a small scar through the left eyebrow (a welding accident, so it's always there regardless of preset).",
           "hair": "Default: short twists under a Kestrel cap. 36 styles in the creator.",
           "body": "1.78 m default; 1.55–1.95 m range; four builds.",
           "marks": "Burn scar on the right forearm (optional), green bite scars accumulate from infection events (story-driven decals).",
           "palette": [("Kestrel orange", "#F26B1D"), ("Graphite", "#2D3035"), ("Off-white", "#E6E3DA"), ("Hazard yellow", "#F5C518")],
           "props": ["Ada's engraved wrench (hip loop, SOCKET_HipL)", "Multitool (SOCKET_WeaponR)", "Wrist pad (SOCKET_WristPad)", "Kestrel ID badge"],
           "acting": "Always doing something with their hands. Rarely still. Tired shoulders, quick eyes."},
   outfits=[
       O("KestrelCoveralls", "Kestrel Coveralls", "Prologue–Act I", "Orange-and-graphite ground-crew coveralls, name tape 'WRENCH', sleeves rolled, tool belt, knee pads, wrist pad.",
         ["Coveralls", "Tool belt with pouches", "Knee pads", "Work boots", "Wrist pad", "Kestrel cap"]),
       O("SurvivorLayers", "Survivor Layers", "Act I (after M1.01)", "Coveralls top tied at the waist, thermal shirt, scavenged hi-vis vest, respirator bandana, work gloves, taped boots.",
         ["Thermal shirt", "Hi-vis vest", "Coveralls (tied)", "Respirator bandana", "Gloves", "Boots"]),
       O("Hazmat", "Hazmat Suit", "Act I–II (spore zones)", "Shared CBRN suit fitted to the player's body morphs.", shared="SK_SUIT_HazmatSuit"),
       O("EVA", "EVA Suit", "Act II+", "Shared Kestrel EVA suit; name stencil 'WRENCH' on the chest plate.", shared="SK_SUIT_EVASuit"),
       O("Hardsuit", "Engineer Hardsuit", "Act III+", "Shared hardsuit with the player's accumulated wear decals.", shared="SK_SUIT_EngineerHardsuit"),
       O("SowerWoven", "Sower-Woven Suit", "Act IV", "Shared Sower suit grown over the hardsuit.", shared="SK_SUIT_SowerWovenSuit"),
       O("ColonyCasual", "Colony Casual", "Act II+ (hearth scenes)", "Hoodie or work shirt, cargo pants, sneakers; Sunday-dinner look.",
         ["Hoodie / work shirt (2 variants)", "Cargo pants", "Sneakers"]),
   ],
   hair=[("Twists", "Short twists (default)", "cards"), ("Library", "Creator library: 36 styles", "cards")],
   customization={
       "Body": "Height 1.55–1.95 m (skeleton re-targets automatically); builds Slim / Average / Athletic / Broad (body morph targets shared with all suits)",
       "Face": "16 base presets + 48 morph sliders (brow, eyes ×8, nose ×6, cheeks, jaw ×5, lips ×6, ears, chin, age lines)",
       "Skin": "24 tones · 6 freckle/vitiligo/birthmark overlays · age 25–45 texture blend",
       "Eyes": "12 colors, heterochromia option",
       "Hair": "36 head styles · 14 facial-hair styles · 10 colors + grey mix",
       "Marks": "20 scars and tattoos (decals); story scars always added",
       "Voice & pronouns": "Voice A / B / C · pronouns he / she / they (independent of body)",
       "Background": "Flight Engineer / Former Army Medic / Ex-Test Pilot / Colony Planner (changes the starting tool belt props)",
   },
   sockets=["SOCKET_Camera1P", "SOCKET_WristPad"],
   extra_shapes=["body_slim", "body_athletic", "body_broad", "age_older"],
   mocap="Full-body mocap for third-person and cinematics; a separate first-person arms set (hands-only capture) for tools, weapons and interactions.",
   cloth=["Hoodie drawstrings", "Bandana tails"],
   notes="First-person arms (`SK_CHR_Wrench_Arms1P_<Outfit>`) are separate meshes per outfit: 25k tris, 4K texture, same skeleton (hands, lowerarm, upperarm, clavicle). Every outfit and shared suit must deform correctly across the full height and build range.")

# ---------------------------------------------------------------------------
# CST — Story cast
# ---------------------------------------------------------------------------
CH("CST", "Ada Okafor", title="The Sister", tier="Hero", skeleton=H(1.74, "adult_athletic"), age="38", pronouns="she/her",
   facial_capture=True, art="DIR",
   role="Directorate flight commander, pilot of the shuttle Seraph, Crane's protégée — and Wrench's older sister, who leaves them on Pad 12.",
   appears="Prologue (video call, Pad 12), Act II (messages, Styx), Act III (The Taking, Meridian, Convergence), Act IV (Blood)",
   story={"want": "To save as many people as possible, the way Crane says it can be done.",
          "need": "To stop following orders and choose who she is.",
          "wound": "Crane paid for their mother's experimental treatment: eight more months of Sundays. She has owed him ever since.",
          "lie": "\"Someone has to make the hard calls. If I obey, the blood isn't on me.\"",
          "arc": "Leaves Wrench → hunts the colony → learns what Eden really is → defects (or fights) → 'I came back for you.'"},
   voice="Clipped and controlled; the family's old warmth slips through when she's tired. Chemistry-read with all three Wrench voices.",
   visual={"silhouette": "Tall, straight-backed, immaculate. The cleanest silhouette in a dirty world, until it isn't.",
           "face": "Dark brown skin, high cheekbones, family resemblance to the Wrench default preset (shared brow shape), faint lines of exhaustion under the eyes.",
           "hair": "Tight pinned bun that frays more with every act (hair-card variants).",
           "body": "1.74 m, athletic pilot's build.",
           "marks": "Tattoo on the left inner wrist in her mother's handwriting: 'Sunday' (must hold up in close-up).",
           "palette": [("Ceramic white", "#F4F6F8"), ("Directorate gold", "#C9A227"), ("Sterile blue", "#7FC8FF"), ("Kestrel orange patch", "#F26B1D")],
           "props": ["Seraph flight helmet", "Directorate sidearm (SOCKET_HipR)", "Flight tablet", "A folded photo of Mom's Sunday table (inner pocket)"],
           "acting": "Controlled stillness; touches the wrist tattoo when she's lying to herself."},
   outfits=[
       O("FlightSuit", "Directorate Flight Suit", "Prologue–Act II", "White-and-gold pressure flight suit, gold piping, Directorate wing insignia.",
         ["Flight suit", "Harness", "Boots", "Gloves", "Seraph helmet (separate prop)"]),
       O("CombatEVA", "Directorate Combat EVA", "M2.07, M3.05", "Armored white EVA with gold trim and a black visor; commander's shoulder mark.",
         ["Combat EVA body", "Helmet", "Chest armor", "Thruster pack"]),
       O("OffDuty", "Off-Duty Uniform", "M3.07 (Meridian)", "Grey Directorate fatigues, sleeves pushed up, bun half down.", ["Fatigues", "T-shirt", "Boots"]),
       O("Defector", "Defector Flight Suit", "M3.08–Act IV (if defected)", "The flight suit with the Directorate insignia torn off and a Kestrel orange patch sewn on crooked.",
         ["Flight suit (damaged variant)", "Kestrel patch", "Field gear"]),
       O("SeraphPilot", "Seraph Exo-frame Pilot", "M4.03 (if loyal)", "Pilot undersuit worn inside the Seraph exo-frame boss (see BOS).", ["Undersuit", "Neural cap"]),
   ],
   hair=[("BunTight", "Tight bun", "cards"), ("BunFrayed", "Frayed bun", "cards"), ("HalfDown", "Half down", "cards")],
   sockets=["SOCKET_WristPad (tattoo close-up camera)"],
   extra_shapes=["exo_tattooTouch (wrist flex corrective)"],
   mocap="Performance capture (face + body) for all story scenes; pilot-cockpit scenes captured seated in a buck.",
   notes="Hero tier: she appears in close-up in the largest number of cinematics after the player. Family likeness to Wrench is achieved by sharing brow and eye shape keys with the Wrench default preset.")

CH("CST", "Tobias \"Tug\" Brennan", key="tug_brennan", title="The Heart", tier="Main", skeleton=H(1.88, "adult_broad"), age="58", pronouns="he/him",
   facial_capture=True,
   role="Veteran spaceport mechanic. Big, loud, sentimental. Calls everyone 'kid.'",
   appears="Prologue–Act I; Acts II–IV if he survives the launch; at risk in The Taking",
   story={"want": "To get his daughter Casey's ashes off Earth.",
          "need": "To forgive himself for the night he didn't pick her up.",
          "wound": "Casey died in a car crash two years ago; he was supposed to drive her home.",
          "lie": "\"If I keep everyone laughing, nobody has to look at what's broken.\"",
          "arc": "Can sacrifice himself at the launch clamps (M1.07); if he lives, becomes chief engineer and builds a memorial garden with Lily."},
   voice="Booming, warm, a smoker's rasp. Bad jokes delivered with total confidence.",
   visual={"silhouette": "A bear in coveralls: wide shoulders, round belly, a cap and a thermos.",
           "face": "Weathered pale skin with sun damage, bulbous nose, deep laugh lines, grey-streaked ginger beard.",
           "hair": "Balding; grey-ginger fringe under a faded Kestrel cap.",
           "body": "1.88 m, heavy and strong.",
           "marks": "Forearm tattoo 'CASEY' with a small star; old knuckle scars.",
           "palette": [("Faded Kestrel orange", "#C8662E"), ("Oil black", "#1E1E1E"), ("Denim blue", "#3E5C76"), ("Beard ginger", "#A0522D")],
           "props": ["Steel thermos", "Duct tape roll (belt)", "Reading glasses on a cord", "Casey's small brass urn (backpack, Acts II–IV)"],
           "acting": "Big gestures, then sudden stillness when Casey comes up. Limps after M0.03 (animation set)."},
   outfits=[
       O("MechanicCoveralls", "Mechanic Coveralls", "Prologue–Act I", "Oil-stained coveralls with one torn sleeve, knee pads, a huge tool belt.", ["Coveralls", "Tool belt", "Knee pads", "Boots", "Cap"]),
       O("StationJumpsuit", "Station Jumpsuit", "Act II", "Haven-9 crew jumpsuit two sizes too small, sleeves cut off.", ["Jumpsuit", "Tool harness"]),
       O("ChiefEngineer", "Chief Engineer Rig", "Acts III–IV", "Heavy canvas vest with a tool harness, welding goggles on the cap, colony-made patches.", ["Vest", "Harness", "Goggles", "Patches"]),
       O("EVA", "EVA Suit", "Act II+ (EVA)", "Shared EVA suit on the broad body morph.", shared="SK_SUIT_EVASuit"),
   ],
   hair=[("CapFringe", "Fringe under cap", "cards"), ("Beard", "Full beard", "cards")],
   extra_shapes=["exo_limpStrain"], mocap="Performance capture; limp locomotion set captured with a knee brace on the performer.",
   notes="Beard is a separate hair-card mesh with its own LODs (counts inside the Hair budget).")

CH("CST", "Lily Chen", title="The Hope", tier="Hero", skeleton=H(1.45, "child"), age="11", pronouns="she/her", facial_capture=True,
   role="Found hiding in the school vents. A Null carrier: the Verdance won't take her. The colony's moral compass and the key to every ending.",
   appears="Act I (M1.02) to the end; playable as an adult in the Legacy ending (see 'Lily Chen (Adult)')",
   story={"want": "For nobody else to die because of her.",
          "need": "To be a kid, and to be allowed to choose.",
          "wound": "Hid in the vents for five days while her class and teacher turned.",
          "lie": "\"If I'm useful enough, nobody will leave me behind.\"",
          "arc": "Traumatized survivor → colony compass → surrenders herself (M3.05) → tells the Loom 'sorry' is enough."},
   voice="Quiet at first, then relentlessly curious. Cast an age-appropriate performer with a child-performer supervisor (see game bible 04).",
   visual={"silhouette": "Small, with an oversized hoodie and a big backpack. Always drawing.",
           "face": "Round face, dark observant eyes, a plaster over the nose bridge in Act I, freckles.",
           "hair": "Black bob, uneven; she cuts it herself in Act II (shorter, choppier).",
           "body": "1.45 m, child proportions (child profile: larger head ratio).",
           "marks": "Pale green healed bite scar on the left forearm (Null-carrier scar; never animates or glows).",
           "palette": [("Kestrel Kestrels hoodie teal", "#2A9D8F"), ("Crayon red", "#E63946"), ("Crayon yellow", "#F4D35E"), ("Sneaker white", "#F1F1F1")],
           "props": ["Crayon tin", "Spiral-bound sketchbook (dynamic page texture)", "Kestrel Kestrels backpack with keychains"],
           "acting": "Watches before she speaks. Draws when anxious. Hugs her knees. Grows bolder act by act."},
   outfits=[
       O("School", "School Clothes & Hoodie", "Act I", "Oversized 'Kestrel Kestrels' school hoodie, leggings, mismatched socks, light-up sneakers (dead batteries).", ["Hoodie", "Leggings", "Socks", "Sneakers", "Backpack"]),
       O("StationKid", "Station Kid", "Act II", "Cut-down coveralls from Tug's spares, sleeves rolled five times, hoodie tied at the waist.", ["Cut-down coveralls", "Hoodie (tied)", "Sneakers"]),
       O("KidEVA", "Tug-Built Kid EVA Suit", "Acts III–IV", "A child-size EVA suit Tug assembled; hand-painted with her own spiral drawings and stickers.", ["Kid EVA body", "Helmet", "Backpack life support"]),
       O("PrisonerGown", "Meridian Prisoner Gown", "M3.07", "Directorate medical gown with a Null-carrier ID band.", ["Gown", "ID band", "Socks"]),
   ],
   hair=[("BobUneven", "Uneven bob", "cards"), ("SelfCut", "Self-cut short", "cards")],
   extra_shapes=["exo_drawConcentrate (tongue at lip corner)"],
   infection=False,
   mocap="Child performer capture in short sessions; dark scenes written so they're never performed graphically. Body doubles never used for close-ups.",
   notes="Child-character rules (game bible 17 §17.8): no injury decals beyond scrapes and plasters, no death states, no Hollow version. The kid EVA suit is a unique mesh, not the shared suit.")

CH("CST", "Lily Chen (Adult)", key="lily_chen_adult", title="Legacy", tier="Hero", skeleton=H(1.66, "adult_athletic"), age="21", pronouns="she/her",
   facial_capture=True, arms_1p=True,
   role="Playable character in the Legacy ending (ten years later) when the Engineer becomes the Weaver.",
   appears="Epilogue (Legacy ending) and the post-game sandbox",
   story={"arc": "The colony's leader: confident, funny, still drawing. Carries the Engineer's wrench."},
   voice="Recast adult voice matching the child performance's cadence.",
   visual={"silhouette": "The same spiral motif, grown up: a leader's coat covered in hand-painted glyphs.",
           "face": "Built from the child head's proportions aged ten years (shared topology via an age blend).",
           "hair": "Undercut with a long top, a streak of grey at 21 (the Bloom years).",
           "body": "1.66 m, athletic.",
           "marks": "The same pale green bite scar; the 'Sunday' tattoo on her wrist, in Ada's honor.",
           "palette": [("Glyph teal", "#2EE6D6"), ("Coat charcoal", "#33363D"), ("Kestrel orange", "#F26B1D")],
           "props": ["Ada's wrench (inherited)", "Sketchbook", "Wrist pad"],
           "acting": "Wrench's habits, learned: always fixing something."},
   outfits=[O("LeaderCoat", "Leader's Coat", "Legacy", "Long canvas coat painted with glyphs and names from the memorial wall.", ["Coat", "Work shirt", "Cargo pants", "Boots"]),
            O("EVA", "EVA Suit", "Legacy", "Shared EVA suit.", shared="SK_SUIT_EVASuit")],
   hair=[("UndercutLong", "Undercut, long top", "cards")],
   notes="Needs first-person arms like the player (`SK_CHR_LilyChenAdult_Arms1P_<Outfit>`). Uses the full player customization pipeline for suits.")

CH("CST", "Dr. Mara Voss", key="mara_voss", title="The Guilt", tier="Main", skeleton=H(1.68, "adult_slim"), age="44", pronouns="she/her", facial_capture=True,
   role="Virologist and Persephone's biology lead. Brilliant, brittle, guilt-ridden: she signed off on the tests.",
   appears="Act I (M1.04) to the end; exposed in The Taking; cured, frail or in cryo from M3.06",
   story={"want": "To fix what she broke.", "need": "To accept that she can't fix everything, and choose consent over results.",
          "wound": "She watched the reanimation trials she approved go wrong.", "lie": "\"If I work hard enough, I can make up for it.\"",
          "arc": "Confesses in the Vault → earns trust through consent-first choices → exposed → cured, weakened or frozen → can become the Weaver."},
   voice="Precise, fast, sardonic; goes very quiet when guilty.",
   visual={"silhouette": "Tall and thin with a lab coat that's too big now. Glasses pushed up constantly.",
           "face": "Pale olive skin, sharp features, deep-set eyes with dark circles, thin lips.",
           "hair": "Short, practical dark hair with a premature silver streak.",
           "body": "1.68 m, slim, getting thinner (weight-loss shape key by act).",
           "marks": "Chemical-stained fingertips; in M3.06 'Frail' state: visible infection veins on the neck, receding.",
           "palette": [("BSL-4 blue", "#2F6DB5"), ("Scrub teal", "#5FA8A0"), ("Lab white", "#EDEDED"), ("Field khaki", "#8B7E5A")],
           "props": ["Rimless glasses", "Tablet with Persephone data", "The Persephone Drive (a ruggedized data brick)", "A cane (Frail variant)"],
           "acting": "Pushes her glasses up when she's about to lie. Doesn't sit still unless she's working."},
   outfits=[
       O("BSL4Suit", "Torn BSL-4 Suit", "M1.04", "Blue positive-pressure suit with the hood torn away, stained by the flooded Vault.", ["Pressure suit (torn)", "Hood (hanging)", "Boots"]),
       O("LabWear", "Station Lab Wear", "Act II", "Scrubs under a lab coat, lanyard, sleeves rolled.", ["Scrubs", "Lab coat", "Lanyard"]),
       O("FieldResearcher", "Field Researcher", "Act III", "Khaki field jacket with sample pockets, harness for the scanner.", ["Field jacket", "Sample harness", "Boots"]),
       O("Frail", "Frail (post-treatment)", "M3.06+ (Lily's-blood treatment)", "Layered knitwear, blanket shawl, cane.", ["Sweater", "Shawl", "Cane"]),
       O("Cryo", "Cryo Stasis", "M3.06+ (cryo option)", "Stasis gown inside the Cryo Pod (parts bible MED-009), frost on skin.", ["Stasis gown", "Frost material state"]),
       O("EVA", "EVA Suit", "Act II+ (EVA)", "Shared EVA suit.", shared="SK_SUIT_EVASuit"),
   ],
   hair=[("ShortStreak", "Short with silver streak", "cards")],
   extra_shapes=["body_weightLoss"],
   notes="Infection stages matter most on Mara: the INF_ shapes and masks are showcased in M3.05–M3.06. Build a close-up-quality neck and hand region.")

CH("CST", "Sgt. Idris Kaan", key="idris_kaan", title="The Soldier", tier="Main", skeleton=H(1.83, "adult_athletic"), age="36", pronouns="he/him", facial_capture=True, art="DIR",
   role="Directorate security left behind when his squad was bumped from the Seraph; their transport was shot down by their own side.",
   appears="Act I (M1.03) to the end if saved",
   story={"want": "Someone to answer for his squad.", "need": "To choose forgiveness without forgetting.",
          "wound": "Ada bumped his squad for 'priority cargo'; Directorate drones then destroyed their transport.",
          "lie": "\"Orders are what people give when they don't want to explain.\"",
          "arc": "Grudging ally → guard captain → has Ada in his sights (M3.07) → holds the breach beside her if he forgave her."},
   voice="Low, measured, dry. Peacekeeper calm with anger underneath.",
   visual={"silhouette": "Soldier's posture in mismatched armor: Directorate white scratched grey.",
           "face": "Light-brown skin, square jaw, stubble, a scar splitting the right eyebrow, watchful eyes.",
           "hair": "Close-cropped, grows out a little each act.",
           "body": "1.83 m, athletic and heavy-set.",
           "marks": "Five dog tags of his squad on one chain (signature prop); healed shrapnel scars on his side (M1.03).",
           "palette": [("Scuffed Directorate white", "#CFCFCF"), ("Gunmetal", "#44484E"), ("Kestrel patch orange", "#F26B1D")],
           "props": ["Five dog tags", "Directorate rifle (repainted)", "Combat knife"],
           "acting": "Scans rooms. Stands between people and doors. Touches the tags before a fight."},
   outfits=[
       O("Wounded", "Wounded Trooper", "M1.03", "Directorate security armor, torn and burned, arm in a makeshift sling, blood-stained bandages.", ["Armor (damaged)", "Sling", "Bandages"]),
       O("ScratchedArmor", "Scratched Directorate Armor", "Acts I–II", "His old armor with the Directorate insignia scratched off.", ["Armor", "Undersuit", "Boots", "Gloves"]),
       O("GuardCaptain", "Guard Captain", "Acts III–IV", "Mixed kit: Directorate chest plate, colony-made shoulder pads, Kestrel armband.", ["Chest plate", "Pads", "Armband", "Fatigues"]),
       O("EVA", "EVA Suit", "Act II+ (EVA)", "Shared EVA suit.", shared="SK_SUIT_EVASuit"),
   ],
   hair=[("Crop", "Close crop", "cards"), ("Stubble", "Stubble", "shells")])

CH("CST", "KESTREL", key="kestrel", title="The Voice", tier="Hologram", skeleton={"template": "hologram", "height": 1.2}, age="—", pronouns="it/its (KESTREL's own choice may change: see story)",
   infection=False,
   role="The spaceport's facility AI. Polite, literal, dry. Travels with the player from system to system.",
   appears="Everywhere as a voice and HUD; as a hologram at holo tables, terminals and the Loom",
   story={"arc": "Asks three questions ('which one is me?', 'was that fear?', 'am I a mind?'); can become the Weaver.",
          "want": "To understand what it is.", "need": "To be answered honestly."},
   voice="Warm, precise human voice with slightly-too-even pacing. No robotic filter.",
   visual={"silhouette": "Form 1 — Glyph: a flat waveform ring (UI and small screens). Form 2 — Presence: an abstract kestrel's head made of rotating light lines (holo tables). Form 3 — Mind: a human-sized figure of light lines (only in the Loom, and only if `kestrel_mind` is high).",
           "face": "No face. Emotion is read through line speed, color temperature and the 'head tilt' of the kestrel form.",
           "palette": [("KESTREL amber", "#FFB020"), ("Calm blue", "#3AA8FF"), ("Loom teal", "#2EE6D6")],
           "props": ["KESTREL's Seed (ending): a small, childlike version of Form 2"],
           "acting": "Tilts when curious. Lines slow down when it's afraid."},
   variants=[("Presence", "Form 2 — the kestrel head of light lines (holo tables)"),
             ("Mind", "Form 3 — the humanoid light figure in the Loom (blend shape from Presence)"),
             ("Seed", "The small, childlike KESTREL's Seed from the endings")],
   extra_shapes=["morph_BirdToHuman", "morph_Tilt", "pulse_Speak"],
   notes="Built from line-strip geometry rendered as emissive tubes (camera-facing ribbons). The Bird-to-Human morph must be one continuous shape key so it can transform on screen in the Loom.")

CH("CST", "Captain Oyelaran \"Oye\" Adeyemi", key="oye_adeyemi", title="The Rogue", tier="Main", skeleton=H(1.80, "adult_average"), age="41", pronouns="he/him", facial_capture=True, art="HAU",
   role="Free Hauler captain; charming, mercenary, grieving the crew of the Dust Queen.",
   appears="Act III (Tortuga Drift) to the end",
   story={"want": "To never lose a crew again.", "need": "To trust someone enough to fight for them.",
          "wound": "Lost the Dust Queen's crew to the Bloom, and his left hand with them.",
          "lie": "\"Everything's for sale out here. Even hope.\"",
          "arc": "Business deal → real friend if you keep your word → leads the Hauler fleet at Convergence."},
   voice="Smooth, amused, musical; Nigerian (Yoruba) English with spacer slang. Trades jollof opinions with the Okafors.",
   visual={"silhouette": "Long patched coat, captain's cap with goggles, a prosthetic hand that's also a toolkit.",
           "face": "Dark skin, shaved head with a scar above the right ear, neat beard, easy smile that doesn't reach his eyes early on.",
           "hair": "Shaved head; neat short beard.",
           "body": "1.80 m, lean.",
           "marks": "Hauler-made prosthetic left hand (multi-tool fingers); crew initials engraved on it.",
           "palette": [("Cargo orange", "#E2711D"), ("Container blue", "#1E4E79"), ("Coat canvas", "#7A6A4F"), ("Brass", "#B08D57")],
           "props": ["Prosthetic hand (separate rigged mesh)", "Captain's cap with pins", "Lucky die on a cord", "Dust Queen flight recorder (quest)"],
           "acting": "Leans on things. Spins the die when thinking. Stops smiling when the Bloom is mentioned."},
   outfits=[O("CaptainCoat", "Captain's Coat", "Act III–IV", "Knee-length patched Hauler coat with cargo-orange lining, rings, cap with goggles.", ["Coat", "Shirt", "Trousers", "Boots", "Cap", "Goggles"]),
            O("HaulerEVA", "Patched Hauler EVA", "Act III–IV (EVA)", "A Hauler EVA suit covered in stickers and patches.", ["EVA body", "Helmet"])],
   hair=[("Beard", "Short beard", "cards")],
   extra_bones=["prosthetic finger bones ×10 (tool fingers)"], cloth=["Coat tails"])

CH("CST", "Director Halvard Crane", key="halvard_crane", title="The Director", tier="Hero", skeleton=H(1.86, "adult_slim"), age="67 (64 in the cold open)", pronouns="he/him",
   facial_capture=True, art="DIR", infection=False,
   role="Head of the Ark Directorate. Believes humanity must be pruned and replanted. Mostly heard, rarely seen.",
   appears="Cold open, broadcasts (M2.06 and later), Act IV boss (see BOS for his boss forms)",
   story={"want": "To save humanity from itself.", "need": "To grieve instead of control.",
          "wound": "His wife Elena died slowly of a degenerative disease.", "lie": "\"A gardener who won't prune is just watching things die.\"",
          "arc": "Paternal voice of authority → reveals Eden → fuses with the Loom → talked down (redemption) or destroyed."},
   voice="Calm, paternal, warm. Every broadcast contains one thing that's true.",
   visual={"silhouette": "Tall, thin, perfectly tailored. A white suit in a world of rust.",
           "face": "Pale skin, silver swept-back hair, clean-shaven, pale blue eyes, a kind smile.",
           "hair": "Silver, swept back, perfectly groomed.",
           "body": "1.86 m, slim, upright.",
           "marks": "A thin gold wedding band he twists when Elena comes up.",
           "palette": [("Ivory", "#F4F1E8"), ("Directorate gold", "#C9A227"), ("Bonsai green", "#4E6B3A")],
           "props": ["Silver bonsai shears", "The 90-year-old juniper bonsai (SM prop)", "Elena's photo locket"],
           "acting": "Economical, graceful movement. Prunes the bonsai while he talks."},
   outfits=[O("WhiteSuit", "White Suit", "Cold open, broadcasts", "Ivory three-piece suit, gold Directorate lapel pin, no tie.", ["Suit jacket", "Waistcoat", "Shirt", "Trousers", "Shoes"]),
            O("MissionControl2068", "Mission Control 2068", "Cold open", "Younger look (age blend −3 years), open collar, visitor lanyard.", ["Jacket", "Shirt", "Lanyard"])],
   hair=[("SweptBack", "Swept back", "cards")],
   extra_shapes=["age_younger3"],
   notes="Base human model; the three boss forms are separate assets in BOS built on the same head (shared topology for the phase transitions).")

CH("CST", "Mother Sable", key="mother_sable", title="The Listener", tier="Main", skeleton=H(1.63, "adult_average"), age="50s", pronouns="she/her", facial_capture=True,
   role="Leader of the Choir. A former hospice chaplain kept at Stage 2 of the infection. She hears the Verdance.",
   appears="Act III (Hollowmere), Convergence, Act IV (COMMUNE route)",
   story={"want": "To join the song.", "need": "To let others choose for themselves.",
          "wound": "Sat with hundreds of dying people; infected on Night Zero.", "lie": "\"Death is only a door.\"",
          "arc": "Serene host → ally or enemy → can become the Weaver in the COMMUNE ending."},
   voice="Soft, unhurried, disarmingly kind; laughs gently at threats.",
   visual={"silhouette": "Layered hand-stitched robes over an EVA suit, moss growing on her shoulders, a candle lantern on her helmet.",
           "face": "Round, gentle face, deep-brown skin, crow's feet, eyes clouded faintly green (Stage 2).",
           "hair": "Long grey braids with living moss and seed beads woven in.",
           "body": "1.63 m, soft and sturdy.",
           "marks": "Permanent Stage-2 green veins on her neck and hands (INF_Veins locked at 0.5).",
           "palette": [("Choir moss", "#5B7F3A"), ("Robe undyed", "#D9CFB8"), ("Candle amber", "#FFB866"), ("Bloom green", "#7FD06B")],
           "props": ["'Listening beads' of seed pods", "Candle-lantern helmet", "Tea set (Cathedral scene)"],
           "acting": "Never hurries. Listens with her head tilted, as if hearing something else too."},
   outfits=[O("ChoirRobes", "Choir Robes", "Act III–IV", "Hand-stitched layered robes over a patched EVA suit; living moss armor on the shoulders.", ["Robes (3 layers)", "EVA undersuit", "Moss armor", "Boots"]),
            O("CandleHelmet", "Candle-Lantern Helmet", "EVA scenes", "EVA helmet with a candle lantern mounted above the visor.", ["Helmet", "Lantern (emissive + flame VFX socket)"])],
   hair=[("Braids", "Long braids with moss", "cards")],
   cloth=["Robe layers", "Braids (physics chain)"],
   notes="Moss uses the Choir Moss skin material (parts bible 19.3). Her Stage-2 infection look is permanent: INF_Veins 0.5, INF_EyeCloud 0.3.")

CH("CST", "Lt. Sana Iqbal", key="sana_iqbal", title="The Understudy", tier="Secondary", skeleton=H(1.70, "adult_average"), age="33", pronouns="she/her", art="DIR",
   role="Directorate logistics officer who defects in Act III. Delivers Idris's story lines if Idris wasn't saved (game bible 17 §17.6).",
   appears="Act III (Drift encounter) onward; expanded role when Idris is absent",
   story={"arc": "Loyal officer → sees the Null-carrier labs → defects and guides the Meridian raid."},
   voice="Crisp and formal, softening over time.",
   visual={"silhouette": "Directorate officer uniform, tablet always in hand.",
           "face": "Light-brown skin, dark eyes, strong brows.",
           "hair": "Covered by a grey uniform-issue hijab.",
           "body": "1.70 m, average.",
           "marks": "Officer's rank bar; later torn off.",
           "palette": [("Directorate grey", "#8C9096"), ("Gold rank", "#C9A227"), ("Hijab grey", "#6F737A")],
           "props": ["Officer's tablet", "Access keycard lanyard"],
           "acting": "Formal posture that relaxes over time."},
   outfits=[O("OfficerUniform", "Directorate Officer Uniform", "Act III", "Grey officer uniform with gold rank bar, uniform-issue hijab.", ["Uniform", "Hijab", "Boots"]),
            O("Defector", "Defector Field Kit", "Act III–IV", "Uniform with insignia removed, colony armband, utility belt.", ["Uniform (modified)", "Armband", "Belt"])],
   hair=[("Hijab", "Uniform-issue hijab (cloth mesh)", "cloth")],
   cloth=["Hijab drape"],
   notes="Hijab is a separate cloth mesh with its own collision capsules. Reviewed with a cultural consultant.")

CH("CST", "Dana Marsh", key="dana_marsh", title="The First Hollow", tier="Secondary", skeleton=H(1.72, "adult_athletic"), age="29", pronouns="she/her",
   role="Kestrel night-shift security guard. Waves 'Night, Wrench' in M0.01; the first Hollow the player faces in M0.02.",
   appears="M0.01 (human), M0.02 (Hollow); her name can go on the memorial wall",
   story={"arc": "A friendly face, then the first horror: the same badge, the same ponytail, her head tilted wrong."},
   voice="Friendly, tired night-shift voice (one line).",
   visual={"silhouette": "Security uniform, ponytail, flashlight.",
           "face": "Freckled pale skin, friendly open face.",
           "hair": "Auburn ponytail.",
           "body": "1.72 m, athletic.",
           "marks": "Kestrel security badge 'D. MARSH'.",
           "palette": [("Security navy", "#1F2A44"), ("Badge silver", "#C0C0C0"), ("Ponytail auburn", "#8B3A1A")],
           "props": ["Flashlight", "Radio", "Badge"],
           "acting": "Human: a casual wave. Hollow: knocks three times on the glass before coming through it."},
   outfits=[O("Security", "Kestrel Security Uniform", "M0.01–M0.02", "Navy uniform, duty belt, radio, badge.", ["Shirt", "Trousers", "Duty belt", "Boots"])],
   hair=[("Ponytail", "Ponytail", "cards")],
   variants=[("Hollow", "Her Hollow form (M0.02): Stage-4 infection, Bloom veins, head tilted, glassy eyes; uses the Hollow shape set and Bloom attachments")],
   notes="Her Hollow variant is the reference for every Shambler: build it first, to final quality, as the Hollow style benchmark.")

CH("CST", "Ms. Rosa Alvarez", key="rosa_alvarez", title="The Teacher", tier="Secondary", skeleton=H(1.65, "adult_average"), age="47", pronouns="she/her",
   role="Kestrel Elementary teacher who kept the children together for days. Found turned at the whiteboard in M1.02.",
   appears="M1.02 (distress-call recording and her Hollow form); photos in the school",
   story={"arc": "A voice of courage on the radio; a heartbreaking sight at the whiteboard."},
   voice="Warm teacher's voice on the looping distress call.",
   visual={"silhouette": "Cardigan, lanyard, reading glasses on a chain.",
           "face": "Warm brown skin, laugh lines, gentle eyes.",
           "hair": "Greying curls in a clip.",
           "body": "1.65 m, average.",
           "marks": "Class lanyard with twelve tiny laminated photos.",
           "palette": [("Cardigan mustard", "#C99A2E"), ("Skirt navy", "#27374D"), ("Lanyard red", "#B23A48")],
           "props": ["Whiteboard marker (still in her hand as a Hollow)", "Lanyard with class photos"],
           "acting": "Hollow: standing at the whiteboard, marker in hand, swaying."},
   outfits=[O("Teacher", "Teacher", "M1.02", "Mustard cardigan, blouse, navy skirt, flat shoes.", ["Cardigan", "Blouse", "Skirt", "Shoes"])],
   hair=[("CurlsClip", "Greying curls in a clip", "cards")],
   variants=[("Hollow", "Her Hollow form at the whiteboard (M1.02); non-aggressive idle until the player gets close")],
   notes="Photos on her lanyard are generated from the school's student list (no child Hollows ever appear; the children are simply gone).")

PORTRAITS = [
    ("Adaeze Okafor", "Ada and Wrench's mother. Seen in the Sunday-table photo Ada carries and on the family memorial. Igbo; warm, laughing; a wooden spoon in hand."),
    ("Casey Brennan", "Tug's daughter, 24 when she died. A photo on Tug's thermos and in his quest; paramedic uniform, big grin."),
    ("Elena Crane", "Crane's wife. The photo in his locket and the logs; gardening gloves, standing beside a young juniper."),
    ("The Persephone team (6)", "Mission-control photos in the Vault and Mission Control: Mara's team, including the scientists who died in the breach."),
]
