"""Crafting components and raw resources.

Every component is also a 3D prop: it appears as loot, in inventories (icon renders),
floating in zero-G, and on construction stages (component piles on BS1/BS2 frames).
Prop budgets: tris at LOD0, one 512² texture (or shared atlas).
"""


def C(id, name, tier, made_at, ingredients, dims_m, tris, look, *, kind="component", stack=100):
    return {"id": id, "name": name, "tier": tier, "made_at": made_at, "ingredients": ingredients,
            "dims_m": dims_m, "tris": tris, "look": look, "kind": kind, "stack": stack}


COMPONENTS = [
    # --- Act I salvage components (Survivor Scrap set) ---
    C("scrap_metal", "Scrap Metal", "T0", "Grinding props, cars, wrecks", {}, (0.5, 0.1, 0.4), 300,
      "Bent sheet with bolts and flaking paint; 4 random shape variants.", stack=200),
    C("salvaged_wood", "Salvaged Wood", "T0", "Grinding furniture, pallets, fences", {}, (1.0, 0.1, 0.15), 200,
      "Bundle of planks tied with twine; nail holes.", stack=100),
    C("duct_tape", "Duct Tape", "T0", "Looting (stores, hangars)", {}, (0.12, 0.05, 0.12), 250,
      "Silver roll, half used, torn edge.", stack=50),
    C("wiring_bundle", "Wiring Bundle", "T0", "Grinding electronics, vehicles", {}, (0.3, 0.1, 0.3), 400,
      "Coiled mixed-color wires with zip ties.", stack=100),
    C("fabric", "Fabric", "T0", "Looting clothes, tents, seats; Tessari fiber later", {}, (0.4, 0.15, 0.3), 250,
      "Folded canvas-and-cloth bundle.", stack=100),
    # --- Core components (Kestrel Industrial) ---
    C("steel_plate", "Steel Plate", "T1", "Assembler", {"iron_ingot": 21}, (0.6, 0.05, 0.6), 150,
      "Square plate with chamfered corners and a stamped part number.", stack=200),
    C("interior_plate", "Interior Plate", "T1", "Assembler", {"iron_ingot": 3}, (0.6, 0.02, 0.6), 120,
      "Thin light-grey panel with a perforated edge.", stack=200),
    C("construction_component", "Construction Component", "T1", "Assembler", {"iron_ingot": 8}, (0.3, 0.2, 0.3), 400,
      "Bracket-and-bolt kit in a small bundle.", stack=200),
    C("metal_grid", "Metal Grid", "T2", "Assembler", {"iron_ingot": 12, "nickel_ingot": 5, "cobalt_ingot": 3}, (0.6, 0.05, 0.6), 500,
      "Lattice panel of cobalt-steel.", stack=100),
    C("girder", "Girder", "T1", "Assembler", {"iron_ingot": 6}, (1.2, 0.15, 0.15), 200,
      "Short I-beam section.", stack=100),
    C("small_tube", "Small Steel Tube", "T1", "Assembler", {"iron_ingot": 5}, (0.8, 0.06, 0.06), 150,
      "Thin pipe with threaded ends.", stack=200),
    C("large_tube", "Large Steel Tube", "T1", "Assembler", {"iron_ingot": 30}, (1.2, 0.25, 0.25), 300,
      "Heavy pipe section with flanges.", stack=50),
    C("glass_panel", "Glass Panel", "T1", "Assembler", {"silicon_wafer": 15}, (0.6, 0.03, 0.6), 100,
      "Bulletproof glass sheet with a protective film half peeled.", stack=100),
    C("motor", "Motor", "T1", "Assembler", {"iron_ingot": 20, "nickel_ingot": 5}, (0.3, 0.3, 0.4), 800,
      "Electric motor with a cooling-fin housing and shaft.", stack=50),
    C("computer", "Computer", "T1", "Assembler", {"iron_ingot": 0.5, "silicon_wafer": 0.2}, (0.2, 0.03, 0.15), 200,
      "Circuit board module with a heat spreader.", stack=200),
    C("display", "Display", "T1", "Assembler", {"iron_ingot": 1, "silicon_wafer": 5}, (0.3, 0.03, 0.2), 150,
      "Screen module; emissive test pattern when dropped.", stack=100),
    C("power_cell", "Power Cell", "T1", "Assembler", {"iron_ingot": 10, "silicon_wafer": 1, "nickel_ingot": 2}, (0.15, 0.3, 0.15), 300,
      "Cylindrical cell with a charge LED.", stack=100),
    C("solar_cell", "Solar Cell", "T1", "Assembler", {"nickel_ingot": 3, "silicon_wafer": 6}, (0.3, 0.02, 0.3), 100,
      "Dark-blue cell wafer with a grid pattern.", stack=100),
    C("radio_component", "Radio Component", "T1", "Assembler", {"iron_ingot": 8, "silicon_wafer": 1}, (0.2, 0.1, 0.15), 350,
      "Transceiver board with a stubby antenna.", stack=100),
    C("detector_component", "Detector Component", "T2", "Assembler", {"iron_ingot": 5, "nickel_ingot": 15}, (0.2, 0.15, 0.2), 450,
      "Sensor head with a lens.", stack=100),
    C("medical_component", "Medical Component", "T2", "Assembler", {"iron_ingot": 60, "nickel_ingot": 70, "silver_ingot": 20}, (0.3, 0.15, 0.2), 450,
      "Sealed white med-tech module with a red cross.", stack=50),
    C("filter_mesh", "Filter Mesh", "T2", "Assembler", {"nickel_ingot": 4, "bio_plastic": 2}, (0.4, 0.05, 0.4), 250,
      "Pleated filter cartridge; clean white.", stack=100),
    C("bio_plastic", "Bio-Plastic", "T2", "Refinery (from organics)", {"organics": 10}, (0.3, 0.1, 0.3), 150,
      "Stack of translucent amber sheets.", stack=200),
    C("thruster_component", "Thruster Component", "T2", "Assembler", {"iron_ingot": 30, "cobalt_ingot": 10, "gold_ingot": 1, "platinum_ingot": 0.4}, (0.3, 0.3, 0.4), 700,
      "Nozzle-and-injector assembly.", stack=50),
    C("reactor_component", "Reactor Component", "T2", "Assembler", {"iron_ingot": 15, "stone": 20, "silver_ingot": 5}, (0.4, 0.4, 0.4), 600,
      "Shielded canister with radiation stencils.", stack=50),
    C("superconductor", "Superconductor", "T3", "Assembler", {"iron_ingot": 10, "gold_ingot": 2}, (0.4, 0.1, 0.1), 300,
      "Coiled bar in a frosted sleeve (emissive blue edge).", stack=50),
    C("explosives", "Explosives", "T2", "Assembler", {"silicon_wafer": 0.5, "magnesium_powder": 2}, (0.2, 0.15, 0.2), 250,
      "Taped brick with a detonator port.", stack=50),
    C("heat_shield_tile", "Heat Shield Tile", "T1", "Looting (Township warehouse), later Assembler", {"silicon_wafer": 4, "iron_ingot": 1}, (0.2, 0.05, 0.2), 60,
      "Black hexagonal ablative tile.", stack=200),
    # --- Precursor ---
    C("sower_filament", "Sower Filament", "T4", "Loom Node", {"resonance_crystal": 1, "bloom_sample": 4}, (0.6, 0.05, 0.05), 400,
      "Glowing teal fiber coil that slowly breathes (emissive pulse).", stack=50),
    C("living_alloy", "Living Alloy", "T5", "Loom Node (post-game)", {"sower_filament": 2, "titanium_ingot": 10}, (0.4, 0.1, 0.4), 500,
      "Metal plate with pulsing organic veins.", stack=50),
]

RESOURCES = [
    C("iron_ore", "Iron Ore", "T0", "Everywhere (rock, scrap)", {}, (0.3, 0.3, 0.3), 200, "Rust-red rock chunk.", kind="ore", stack=1000),
    C("nickel_ore", "Nickel Ore", "T1", "Asteroids, rocky worlds", {}, (0.3, 0.3, 0.3), 200, "Silver-green rock chunk.", kind="ore", stack=1000),
    C("silicon_ore", "Silicon Ore", "T1", "Deserts, the Moon", {}, (0.3, 0.3, 0.3), 200, "Grey crystalline chunk.", kind="ore", stack=1000),
    C("cobalt_ore", "Cobalt Ore", "T1", "Moon, volcanic worlds", {}, (0.3, 0.3, 0.3), 200, "Deep-blue veined rock.", kind="ore", stack=1000),
    C("titanium_ore", "Titanium Ore", "T2", "Moon, asteroids", {}, (0.3, 0.3, 0.3), 200, "Pale grey metallic rock.", kind="ore", stack=1000),
    C("silver_ore", "Silver Ore", "T2", "Mines (Silver Ridge), asteroids", {}, (0.3, 0.3, 0.3), 200, "Bright-flecked rock.", kind="ore", stack=1000),
    C("gold_ore", "Gold Ore", "T2", "Rare asteroids", {}, (0.3, 0.3, 0.3), 200, "Gold-flecked quartz.", kind="ore", stack=1000),
    C("magnesium_ore", "Magnesium Ore", "T2", "Rocky worlds", {}, (0.3, 0.3, 0.3), 200, "White chalky rock.", kind="ore", stack=1000),
    C("uranium_ore", "Uranium Ore", "T2", "Radioactive zones", {}, (0.3, 0.3, 0.3), 200, "Dark rock with a faint green glow.", kind="ore", stack=1000),
    C("platinum_ore", "Platinum Ore", "T3", "Rare asteroids", {}, (0.3, 0.3, 0.3), 200, "Heavy silver-white nugget.", kind="ore", stack=1000),
    C("ice", "Ice", "T0", "Poles, ice worlds, comets", {}, (0.3, 0.3, 0.3), 150, "Translucent blue chunk (refraction material).", kind="ore", stack=1000),
    C("stone", "Stone", "T0", "Everywhere", {}, (0.3, 0.3, 0.3), 150, "Grey gravel chunk.", kind="ore", stack=1000),
    C("organics", "Organics", "T0", "Plants, fauna, food waste", {}, (0.3, 0.2, 0.3), 200, "Bundle of plant matter.", kind="resource", stack=500),
    C("bloom_sample", "Bloom Sample", "T1", "Hollows, Bloom Hearts", {}, (0.15, 0.2, 0.15), 250,
      "Sealed specimen jar with green growth (pulsing emissive). Handling without gloves adds infection.", kind="resource", stack=50),
    C("resonance_crystal", "Resonance Crystal", "T3", "Sower ruins, Bloom Hearts", {}, (0.2, 0.35, 0.2), 300,
      "Teal crystal with inner glyph light.", kind="resource", stack=50),
    C("he3_canister", "He-3 Canister", "T3", "Moon, gas giants", {}, (0.3, 0.5, 0.3), 400, "Insulated canister with a magenta band.", kind="fuel", stack=20),
    C("uranium_rod", "Uranium Fuel Rod", "T2", "Refinery", {"uranium_ore": 100}, (0.1, 1.0, 0.1), 150, "Sealed rod with a hazard band.", kind="fuel", stack=20),
    C("diesel_canister", "Fuel Canister", "T0", "Looting; distilled ethanol later", {}, (0.3, 0.45, 0.15), 300, "Red jerrycan.", kind="fuel", stack=10),
    C("iron_ingot", "Iron Ingot", "T0", "Refinery / Scrap Recycler", {"iron_ore": 1.4}, (0.3, 0.08, 0.1), 60, "Stamped ingot.", kind="ingot", stack=1000),
    C("nickel_ingot", "Nickel Ingot", "T1", "Refinery", {"nickel_ore": 2.5}, (0.3, 0.08, 0.1), 60, "Stamped ingot.", kind="ingot", stack=1000),
    C("silicon_wafer", "Silicon Wafer", "T1", "Refinery", {"silicon_ore": 1.4}, (0.2, 0.01, 0.2), 60, "Round wafer.", kind="ingot", stack=1000),
    C("cobalt_ingot", "Cobalt Ingot", "T1", "Refinery", {"cobalt_ore": 3.3}, (0.3, 0.08, 0.1), 60, "Blue-tinted ingot.", kind="ingot", stack=1000),
    C("titanium_ingot", "Titanium Ingot", "T2", "Refinery", {"titanium_ore": 2.0}, (0.3, 0.08, 0.1), 60, "Matte ingot.", kind="ingot", stack=1000),
    C("silver_ingot", "Silver Ingot", "T2", "Refinery", {"silver_ore": 10}, (0.3, 0.08, 0.1), 60, "Bright ingot.", kind="ingot", stack=1000),
    C("gold_ingot", "Gold Ingot", "T2", "Refinery", {"gold_ore": 100}, (0.3, 0.08, 0.1), 60, "Gold ingot.", kind="ingot", stack=1000),
    C("platinum_ingot", "Platinum Ingot", "T3", "Refinery", {"platinum_ore": 200}, (0.3, 0.08, 0.1), 60, "White-silver ingot.", kind="ingot", stack=1000),
    C("magnesium_powder", "Magnesium Powder", "T2", "Refinery", {"magnesium_ore": 140}, (0.2, 0.15, 0.2), 120, "Sealed powder pouch.", kind="ingot", stack=1000),
]
