"""Handheld equipment, suits, suit modules and drones.

First-person (1P) viewmodels are skeletal meshes (SK_) with a shared weapon skeleton;
third-person (3P) world models are simplified copies used on characters and as loot.
"""


def E(id, name, kind, tier, dims_m, *, stats=None, tris_1p=None, tris_3p=None, tex="2K set",
      bones=(), sockets=(), moving=(), emissive=(), vfx=(), notes="", art="IND", unlock=""):
    return {"id": id, "name": name, "kind": kind, "tier": tier, "dims_m": dims_m, "stats": stats or {},
            "tris_1p": tris_1p, "tris_3p": tris_3p, "tex": tex, "bones": list(bones), "sockets": list(sockets),
            "moving": list(moving), "emissive": list(emissive), "vfx": list(vfx), "notes": notes,
            "art": art, "unlock": unlock}


GUN_BONES = ("root", "trigger", "mag")
GUN_SOCKETS = ("grip_R (right-hand IK)", "support_L (left-hand IK)", "muzzle", "eject", "sight (ADS camera)", "rail_light")

EQUIPMENT = [
    # ------------------------------------------------------------------ tools
    E("multitool", "Multitool", "Tool", "T0", (0.45, 0.25, 0.12),
      stats={"modes": "Weld · Grind · Scan · Mining Laser (Mk2) · Plasma Cutter (Mk3)", "tiers": "Mk1–Mk4"},
      tris_1p=35000, tris_3p=8000, bones=("root", "trigger", "mode_dial", "emitter_head", "canister"),
      sockets=("grip_R", "support_L", "emitter (VFX origin)", "screen (mode display)"),
      moving=["Emitter head rotates to the selected mode (0.3 s)", "Mode dial clicks", "Gas canister gauge"],
      emissive=["Mode screen", "Emitter glow (color per mode)"], vfx=["Weld arc", "Grind sparks", "Scan pulse", "Mining beam"],
      notes="The player's signature object: visible 95% of play. Four tier variants (Mk1–Mk4) share the skeleton; each tier adds parts (heat sinks, lens rings). Wear decals accumulate with play time."),
    E("hand_drill", "Hand Drill", "Tool", "T1", (0.6, 0.3, 0.2), stats={"mining_rate": "1× (Mk1) → 3× (Mk4)"},
      tris_1p=25000, tris_3p=6000, bones=("root", "trigger", "bit"), sockets=("grip_R", "support_L", "bit_tip"),
      moving=["Drill bit spins"], vfx=["Rock debris", "Dust"], notes="Chunky two-handed drill; the bit has 4 upgrade variants."),
    E("harvester", "Harvester", "Tool", "T1", (0.5, 0.2, 0.12), stats={"gathers": "plants, alien flora, Bloom samples"},
      tris_1p=18000, tris_3p=5000, bones=("root", "trigger", "blades"), sockets=("grip_R", "blade_tip", "sample_port"),
      moving=["Cutter blades scissor"], notes="Sample canister on the side fills visibly (Bloom samples glow green)."),
    E("binoculars", "Binoculars", "Tool", "T0", (0.18, 0.08, 0.14), stats={"zoom": "8×; Mk2 marks POIs"},
      tris_1p=8000, tris_3p=2000, bones=("root", "focus"), sockets=("grip_R", "grip_L", "view (camera)"),
      moving=["Focus wheel"], notes="Open-world scouting tool: tag points of interest from distance. Scratched lenses (overlay when looking through)."),
    # ------------------------------------------------------------------ melee
    E("adas_wrench", "Ada's Wrench", "Melee", "T0", (0.45, 0.04, 0.1), stats={"damage": 35, "rpm": 70, "noise_db": 20},
      tris_1p=6000, tris_3p=1500, tex="1K set", bones=("root",), sockets=("grip_R", "impact_point"),
      notes="Story item; never breaks. Engraving on the handle: 'For the kid who fixes everything.' The engraving must be legible in the inspect animation."),
    E("fire_axe", "Fire Axe", "Melee", "T0", (0.9, 0.05, 0.3), stats={"damage": 60, "rpm": 45, "durability": 300},
      tris_1p=6000, tris_3p=1500, tex="1K set", bones=("root",), sockets=("grip_R", "grip_L", "impact_point"),
      notes="Red head with chipped paint; blood/Bloom grime overlay."),
    E("crowbar", "Crowbar", "Melee", "T0", (0.75, 0.03, 0.08), stats={"damage": 40, "rpm": 60, "utility": "pries doors and crates"},
      tris_1p=4000, tris_3p=1000, tex="1K set", bones=("root",), sockets=("grip_R", "impact_point")),
    E("riot_baton", "Riot Baton", "Melee", "T1", (0.6, 0.04, 0.04), stats={"damage": 30, "stun": "1.5 s (humans)"},
      tris_1p=5000, tris_3p=1200, tex="1K set", art="DIR", bones=("root",), sockets=("grip_R", "impact_point"),
      emissive=["Shock tip (blue)"], vfx=["Shock arc"], notes="Directorate issue; non-lethal option vs humans."),
    E("sower_blade", "Sower Blade", "Melee", "T4", (0.9, 0.03, 0.12), stats={"damage": 110, "rpm": 60, "bonus": "Resonance damage"},
      tris_1p=15000, tris_3p=3000, art="SOW", bones=("root",), sockets=("grip_R", "impact_point"),
      emissive=["Glyph edge (teal)"], vfx=["Resonance trail"], notes="Grown blade of shell and crystal; the grip adapts to the hand (subtle shape key)."),
    # ------------------------------------------------------------------ improvised
    E("nailgun_rifle", "Nail-Gun Rifle", "Improvised", "T0", (0.8, 0.25, 0.08), stats={"damage": 22, "rpm": 240, "mag": 40, "noise_db": 55},
      tris_1p=28000, tris_3p=6000, art="SCR", bones=GUN_BONES + ("hose",), sockets=GUN_SOCKETS,
      moving=["Nail strip feeds", "Air hose sways"], vfx=["Nail tracer (thin)", "Air puff"],
      notes="Framing nailer bolted to a rifle stock and an air canister; duct-taped grip."),
    E("flare_gun", "Flare Gun", "Improvised", "T0", (0.25, 0.15, 0.05), stats={"damage": 15, "effect": "lights area 30 s; draws Hollows"},
      tris_1p=12000, tris_3p=2500, bones=("root", "trigger", "break_action"), sockets=GUN_SOCKETS[:5],
      vfx=["Flare trail and light"], notes="Orange marine flare pistol."),
    E("pipe_shotgun", "Pipe Shotgun", "Improvised", "T0", (0.7, 0.15, 0.06), stats={"damage": "10 × 8", "rpm": 30, "mag": 1},
      tris_1p=18000, tris_3p=4000, art="SCR", bones=("root", "trigger", "breech"), sockets=GUN_SOCKETS,
      vfx=["Muzzle flash", "Smoke"], notes="Plumbing pipe, hinge and a wood stock."),
    E("rivet_launcher", "Rivet Launcher", "Improvised", "T1", (0.9, 0.25, 0.1), stats={"damage": 45, "rpm": 90, "mag": 12, "effect": "pins Hollows to walls"},
      tris_1p=30000, tris_3p=6500, art="SCR", bones=GUN_BONES + ("piston",), sockets=GUN_SOCKETS,
      moving=["Pneumatic piston cycles"], vfx=["Air blast"], notes="Industrial riveter turned rifle."),
    # ------------------------------------------------------------------ firearms
    E("pistol", "Pistol", "Firearm", "T1", (0.2, 0.14, 0.035), stats={"damage": 30, "rpm": 300, "mag": 15, "noise_db": 140},
      tris_1p=25000, tris_3p=5000, bones=GUN_BONES + ("slide", "hammer"), sockets=GUN_SOCKETS,
      moving=["Slide recoils 25 mm", "Hammer", "Mag drops"], vfx=["Muzzle flash", "Shell ejection"]),
    E("smg", "SMG", "Firearm", "T1", (0.5, 0.2, 0.05), stats={"damage": 20, "rpm": 850, "mag": 30, "noise_db": 135},
      tris_1p=30000, tris_3p=6000, bones=GUN_BONES + ("bolt", "stock"), sockets=GUN_SOCKETS,
      moving=["Bolt cycles", "Folding stock"], vfx=["Muzzle flash", "Shell ejection"]),
    E("assault_rifle", "Assault Rifle", "Firearm", "T2", (0.9, 0.25, 0.06), stats={"damage": 28, "rpm": 650, "mag": 30, "noise_db": 150},
      tris_1p=35000, tris_3p=7000, bones=GUN_BONES + ("bolt", "charging_handle", "selector"), sockets=GUN_SOCKETS,
      moving=["Bolt carrier cycles", "Charging handle", "Fire selector"], vfx=["Muzzle flash", "Shell ejection"],
      notes="Civilian and Directorate (white-gold, DIR) variants share the skeleton."),
    E("pump_shotgun", "Pump Shotgun", "Firearm", "T1", (1.0, 0.2, 0.06), stats={"damage": "12 × 8", "rpm": 60, "mag": 6, "noise_db": 150},
      tris_1p=30000, tris_3p=6000, bones=("root", "trigger", "pump", "shell_gate"), sockets=GUN_SOCKETS,
      moving=["Pump slides 90 mm", "Shells load one by one"], vfx=["Muzzle flash", "Shell ejection"]),
    E("marksman_rifle", "Marksman Rifle", "Firearm", "T2", (1.15, 0.25, 0.07), stats={"damage": 90, "rpm": 60, "mag": 10, "noise_db": 155},
      tris_1p=38000, tris_3p=7000, bones=("root", "trigger", "mag", "bolt_handle", "scope_turret"), sockets=GUN_SOCKETS + ("scope (render target)",),
      moving=["Bolt-action cycle", "Scope turrets"], vfx=["Muzzle flash", "Smoke"], notes="Picture-in-picture scope render target."),
    # ------------------------------------------------------------------ heavy
    E("flamethrower", "Flamethrower", "Heavy", "T2", (1.0, 0.3, 0.15), stats={"damage": "18 per tick", "fuel": 100, "bonus": "×2 vs Bloom", "vacuum": "does not work"},
      tris_1p=35000, tris_3p=7000, bones=("root", "trigger", "igniter", "hose"), sockets=("grip_R", "support_L", "nozzle", "pilot_light"),
      moving=["Igniter clicks", "Fuel hose to back tank"], emissive=["Pilot light"], vfx=["Flame stream", "Heat haze"],
      notes="Back-tank is part of the 3P character attachment (SK_ back slot)."),
    E("grenade_launcher", "Grenade Launcher", "Heavy", "T2", (0.8, 0.25, 0.12), stats={"damage": "120 splash", "rpm": 60, "mag": 6},
      tris_1p=32000, tris_3p=6500, bones=("root", "trigger", "cylinder"), sockets=GUN_SOCKETS,
      moving=["Revolver cylinder rotates 60° per shot"], vfx=["Launch puff"]),
    E("rocket_launcher", "Rocket Launcher", "Heavy", "T3", (1.2, 0.3, 0.15), stats={"damage": "400 splash", "mag": 1},
      tris_1p=30000, tris_3p=6000, bones=("root", "trigger", "sight_flip"), sockets=("grip_R", "support_L", "muzzle", "backblast", "sight"),
      moving=["Flip-up sight"], vfx=["Launch smoke", "Backblast"]),
    # ------------------------------------------------------------------ energy
    E("arc_rifle", "Arc Rifle", "Energy", "T3", (0.9, 0.25, 0.1), stats={"damage": "45 + chain (3)", "rpm": 90, "mag": 20, "bonus": "×2 vs drones and Wardens"},
      tris_1p=38000, tris_3p=7500, bones=GUN_BONES + ("coils",), sockets=GUN_SOCKETS,
      moving=["Capacitor coils rotate while charging"], emissive=["Coils (electric blue)", "Charge meter"], vfx=["Lightning arcs"]),
    E("coil_gun", "Coil Gun", "Energy", "T3", (1.1, 0.2, 0.08), stats={"damage": 130, "rpm": 45, "mag": 8, "effect": "pierces 3 targets"},
      tris_1p=36000, tris_3p=7000, bones=GUN_BONES + ("rings",), sockets=GUN_SOCKETS,
      moving=["Acceleration rings pulse"], emissive=["Rings"], vfx=["Tracer", "Ring flash"]),
    E("laser_cutter", "Laser Cutter", "Energy", "T3", (0.7, 0.2, 0.1), stats={"damage": "30 per tick (beam)", "effect": "also cuts blocks (salvage)"},
      tris_1p=30000, tris_3p=6000, bones=("root", "trigger", "lens"), sockets=("grip_R", "support_L", "emitter"),
      emissive=["Lens"], vfx=["Beam", "Molten impact"]),
    # ------------------------------------------------------------------ precursor
    E("resonance_lance", "Resonance Lance", "Sower", "T4", (1.3, 0.2, 0.12), stats={"damage": 220, "rpm": 30, "mag": 8, "effect": "pierces Warden shields"},
      tris_1p=40000, tris_3p=8000, art="SOW", bones=("root", "trigger", "petals"), sockets=("grip_R", "support_L", "emitter"),
      moving=["Petals open to fire"], emissive=["Glyph channels"], vfx=["Resonance beam", "Ripple"]),
    E("seed_spitter", "Seed-Spitter", "Sower", "T4", (0.8, 0.25, 0.12), stats={"damage": "60 + growth", "effect": "seeds turn Bloom against itself (roots Hollows in place)"},
      tris_1p=36000, tris_3p=7000, art="SOW", bones=("root", "trigger", "pod"), sockets=("grip_R", "support_L", "muzzle"),
      moving=["Seed pod pulses"], emissive=["Pod glow"], vfx=["Seed projectile", "Root burst"]),
    # ------------------------------------------------------------------ throwables
    E("noise_maker", "Noise Maker", "Throwable", "T0", (0.1, 0.1, 0.1), stats={"effect": "lures Hollows for 12 s"},
      tris_1p=3000, tris_3p=800, tex="512 set", art="SCR", sockets=("grip_R", "audio"), emissive=["Blinking LED"],
      notes="Wind-up alarm clock taped to a can."),
    E("frag_grenade", "Frag Grenade", "Throwable", "T1", (0.07, 0.11, 0.07), stats={"damage": "150 splash"},
      tris_1p=3000, tris_3p=800, tex="512 set", bones=("root", "pin", "spoon"), sockets=("grip_R",), moving=["Pin pulls", "Spoon flies"], vfx=["Explosion"]),
    E("molotov", "Molotov", "Throwable", "T0", (0.08, 0.3, 0.08), stats={"damage": "burn 10 s", "bonus": "×2 vs Bloom"},
      tris_1p=3000, tris_3p=800, tex="512 set", art="SCR", sockets=("grip_R", "wick"), vfx=["Wick flame", "Fire pool"]),
    E("emp_grenade", "EMP Grenade", "Throwable", "T2", (0.08, 0.1, 0.08), stats={"effect": "disables drones and electronics 8 s"},
      tris_1p=3500, tris_3p=900, tex="512 set", sockets=("grip_R",), emissive=["Charge ring"], vfx=["EMP dome"]),
    E("spore_bomb", "Spore Bomb", "Throwable", "T2", (0.1, 0.12, 0.1), stats={"effect": "calms Hollows (Choir tech); infects the unprotected"},
      tris_1p=4000, tris_3p=900, tex="512 set", art="SOW", sockets=("grip_R",), emissive=["Pulsing green"], vfx=["Spore cloud"],
      notes="Choir-made: a stitched cloth pouch around a glass bulb."),
    # ------------------------------------------------------------------ consumables
    E("bandage", "Bandage", "Consumable", "T0", (0.08, 0.05, 0.08), stats={"heal": 15}, tris_1p=2000, tris_3p=400, tex="512 set", sockets=("grip_R",)),
    E("medkit", "Medkit", "Consumable", "T1", (0.3, 0.1, 0.2), stats={"heal": 60}, tris_1p=5000, tris_3p=1000, tex="512 set", sockets=("grip_R", "grip_L"), moving=["Lid opens"]),
    E("suppressant", "Suppressant Injector", "Consumable", "T0", (0.15, 0.03, 0.03), stats={"infection": "−10%, halts 20 min"},
      tris_1p=3000, tris_3p=500, tex="512 set", bones=("root", "plunger"), sockets=("grip_R", "needle"), moving=["Plunger"],
      emissive=["Green fluid"], notes="Auto-injector pen; the injection animation into the forearm is iconic (first seen M0.02)."),
    E("antiviral", "Antiviral Cocktail", "Consumable", "T2", (0.15, 0.03, 0.03), stats={"infection": "−40%"},
      tris_1p=3000, tris_3p=500, tex="512 set", bones=("root", "plunger"), sockets=("grip_R", "needle"), emissive=["Amber fluid"]),
    E("null_serum", "Null Serum", "Consumable", "T3", (0.15, 0.03, 0.03), stats={"infection": "cures; 30 min immunity"},
      tris_1p=3000, tris_3p=500, tex="512 set", sockets=("grip_R", "needle"), emissive=["Pale gold fluid"], notes="Made with Lily's consent; label hand-written by Mara."),
    E("loom_serum", "Loom Serum", "Consumable", "T4", (0.15, 0.03, 0.03), stats={"infection": "cures; permanent +resistance"},
      tris_1p=4000, tris_3p=600, tex="512 set", art="SOW", sockets=("grip_R", "needle"), emissive=["Teal glyph light"]),
    E("ration_can", "Ration Can", "Consumable", "T0", (0.08, 0.11, 0.08), stats={"hunger": 25}, tris_1p=1500, tris_3p=300, tex="512 set", sockets=("grip_R",)),
    E("water_bottle", "Water Bottle", "Consumable", "T0", (0.07, 0.22, 0.07), stats={"thirst": 30}, tris_1p=1500, tris_3p=300, tex="512 set", sockets=("grip_R",), notes="Refillable; clean/dirty fill states."),
    E("o2_bottle", "O₂ Bottle", "Consumable", "T1", (0.12, 0.45, 0.12), stats={"o2": "+100 suit O₂"}, tris_1p=3000, tris_3p=600, tex="512 set", sockets=("grip_R", "valve")),
    E("h2_bottle", "H₂ Bottle", "Consumable", "T2", (0.12, 0.45, 0.12), stats={"h2": "+100 jetpack fuel"}, tris_1p=3000, tris_3p=600, tex="512 set", sockets=("grip_R", "valve")),
    # ------------------------------------------------------------------ suits
    E("suit_coveralls", "Work Coveralls", "Suit", "T0", (0.6, 1.8, 0.35), stats={"protection": "none; −10% infection from scratches"},
      tris_3p=30000, tex="2K body set", bones=("UE mannequin-compatible body skeleton",), sockets=("helmet (none)", "backpack", "tool_belt"),
      notes="Kestrel ground-crew coveralls with name tape 'WRENCH'. Unisex body with morph targets."),
    E("suit_hazmat", "Hazmat Suit", "Suit", "T1", (0.65, 1.85, 0.4), stats={"protection": "spores filtered; no vacuum"},
      tris_3p=40000, tex="2K body set", sockets=("helmet", "backpack", "filter_L", "filter_R"),
      notes="Yellow CBRN suit with a clear hood (refraction + condensation)."),
    E("suit_eva", "EVA Suit", "Suit", "T2", (0.75, 1.9, 0.5), stats={"protection": "vacuum, spores; 10 min O₂; jetpack"},
      tris_3p=55000, tex="4K body set", sockets=("helmet", "jetpack", "module_slots ×4", "helmet_light", "wrist_pad"),
      emissive=["Helmet HUD", "Wrist pad", "Status lights"], notes="Kestrel white-and-orange; mag-boots integrated."),
    E("suit_hardsuit", "Engineer Hardsuit", "Suit", "T3", (0.8, 1.95, 0.55), stats={"protection": "vacuum, spores, radiation; armor 40%"},
      tris_3p=65000, tex="4K body set", sockets=("helmet", "jetpack", "module_slots ×6", "shoulder_lamp"),
      emissive=["Helmet HUD", "Seam lights"], notes="Armored plates over the EVA undersuit; tool-mount shoulder."),
    E("suit_sower", "Sower-Woven Suit", "Suit", "T4", (0.75, 1.95, 0.5), stats={"protection": "all hazards; slow self-repair; Hollows ignore at distance"},
      tris_3p=60000, tex="4K body set", art="SOW", sockets=("helmet", "module_slots ×6"),
      emissive=["Glyph veins"], notes="Grown over the Hardsuit: shell plates and filament weave."),
    # ------------------------------------------------------------------ suit modules
    E("mod_jetpack", "Jetpack Module", "Suit Module", "T2", (0.45, 0.6, 0.25), stats={"thrust": "6-DOF; limited above 1 g"},
      tris_3p=12000, tex="2K set", sockets=("back_attach", "nozzles ×4 (VFX)"), vfx=["Thruster puffs"]),
    E("mod_o2_tank", "Extended O₂ Tank", "Suit Module", "T2", (0.3, 0.5, 0.2), stats={"o2": "+10 min"}, tris_3p=4000, tex="1K set", sockets=("back_attach",)),
    E("mod_armor", "Armor Plates", "Suit Module", "T2", (0.5, 0.6, 0.3), stats={"armor": "+20%"}, tris_3p=8000, tex="1K set", sockets=("chest_attach", "shoulder_attach ×2")),
    E("mod_spore_filter", "Spore Filter", "Suit Module", "T1", (0.2, 0.15, 0.15), stats={"spores": "−80% exposure"}, tris_3p=3000, tex="1K set", sockets=("helmet_attach",)),
    E("mod_thermal", "Thermal Lining", "Suit Module", "T2", (0.1, 0.1, 0.1), stats={"temperature": "±40 °C comfort band"}, tris_3p=500, tex="512 set",
      notes="Mostly a material swap on the undersuit (emissive heating lines)."),
    E("mod_scanner", "Scanner Booster", "Suit Module", "T2", (0.15, 0.25, 0.1), stats={"scan_range": "×2"}, tris_3p=3000, tex="1K set", sockets=("shoulder_attach",), moving=["Dish spins"]),
    E("mod_stealth", "Stealth Dampers", "Suit Module", "T3", (0.2, 0.2, 0.15), stats={"noise": "−40% movement noise"}, tris_3p=3000, tex="1K set", sockets=("boot_attach ×2",)),
    # ------------------------------------------------------------------ drones
    E("drone_construction", "Construction Drone", "Drone", "T2", (0.8, 0.4, 0.8), stats={"role": "welds projections, repairs"},
      tris_3p=12000, tex="2K set", bones=("root", "rotor ×4", "arm"), sockets=("weld_tip", "light"), moving=["Rotors ×4", "Welding arm"],
      emissive=["Status ring"], vfx=["Weld sparks"]),
    E("drone_mining", "Mining Drone", "Drone", "T2", (1.0, 0.5, 1.0), stats={"role": "mines ore, returns to the Drone Bay"},
      tris_3p=12000, tex="2K set", bones=("root", "rotor ×4", "drill"), sockets=("drill_tip", "cargo"), moving=["Rotors ×4", "Drill"], vfx=["Debris"]),
    E("drone_defense", "Defense Drone", "Drone", "T3", (0.7, 0.35, 0.7), stats={"role": "patrols; small gun"},
      tris_3p=12000, tex="2K set", bones=("root", "rotor ×4", "gun_yaw", "gun_pitch"), sockets=("muzzle", "light"), moving=["Rotors ×4", "Gun turret"],
      emissive=["Targeting laser"], vfx=["Muzzle flash"]),
    E("drone_scout", "Scout Drone", "Drone", "T2", (0.4, 0.15, 0.4), stats={"role": "remote exploration and signal triangulation (open world)"},
      tris_3p=8000, tex="1K set", bones=("root", "rotor ×4", "camera"), sockets=("camera", "light"), moving=["Rotors ×4", "Camera gimbal"]),
]
