#!/usr/bin/env python3
"""Build the EXODUS PROTOCOL Character Bible from the character catalog.

Usage:
    python3 tools/characters/build.py           # regenerate chapters, JSON and CSV
    python3 tools/characters/build.py --check   # validate only

Generated (docs/character-bible/): 01–10 chapters, data/characters.json,
data/skeletons.json, data/art_tracker_characters.csv. Chapters 00, 11, 12 and the
README are hand-written; the README stats block is refreshed here.
"""

import csv
import json
import re
import sys
from collections import OrderedDict
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
OUT = ROOT / "docs" / "character-bible"
DATA = OUT / "data"
sys.path.insert(0, str(HERE))

import skeletons as SK  # noqa: E402
from catalog import CHARACTERS, GROUPS, LOD_RATIOS, MORE_SURVIVORS, SURVIVOR_KIT, TIERS  # noqa: E402
from catalog.cast import PORTRAITS  # noqa: E402

GENERATED_NOTE = "<!-- GENERATED by tools/characters/build.py from tools/characters/catalog/. Do not edit by hand. -->"
NON_ASSET_OUTFITS = {"KitConversion", "CreatureKit", "EVAConversion", "Swarm", "Construct", "Colossus", "Overgrown",
                     "VaultScientist", "Miner"}
SUBSCRIPTS = str.maketrans("₀₁₂₃₄₅₆₇₈₉", "0123456789")


def pascal(text):
    text = text.translate(SUBSCRIPTS).replace("×", "x").replace("&", "And").replace("'", "").replace("’", "").replace('"', "")
    text = re.sub(r"\(.*?\)", lambda m: m.group(0)[1:-1], text)
    return "".join(p[:1].upper() + p[1:] for p in re.split(r"[^0-9A-Za-z]+", text) if p)


def snake(text):
    text = text.translate(SUBSCRIPTS).replace('"', "").replace("'", "")
    return re.sub(r"[^0-9a-z]+", "_", text.lower()).strip("_")


def fmt(n):
    return f"{int(n):,}"


def lods(tris):
    return [0, 0, 0, 0] if not tris else [max(200, int(round(tris * r))) for r in LOD_RATIOS]


def esc(t):
    return str(t).replace("|", "\\|")


def skeleton_label(spec):
    name = SK.TEMPLATE_NAMES[spec["template"]]
    if spec["template"] == "humanoid":
        return f"{name}, {SK.PROFILES[spec.get('profile', 'adult_average')]['label'].lower()}"
    return name


def size_label(spec):
    t = spec["template"]
    if t == "humanoid":
        return f"{spec['height']:.2f} m tall"
    if t in ("quadruped", "hexapod", "flyer"):
        s = f"{spec['shoulder_h']:.2f} m at the shoulder, {spec['length']:.2f} m long"
        return s + (f", {spec['wings'] * 2:.2f} m wingspan" if spec.get("wings") else "")
    if t == "serpentine":
        return f"{spec['length']:.2f} m long"
    if t == "cetacean":
        return f"{spec['length']:.1f} m long, {spec['girth']:.1f} m girth"
    if t == "drone":
        return f"{spec['size']:.2f} m"
    if t == "hologram":
        return f"{spec['height']:.2f} m"
    return ""


def size_sort(spec):
    return spec.get("height") or spec.get("shoulder_h") or spec.get("length") or spec.get("size") or 0


# --------------------------------------------------------------------------- expand
def expand():
    problems, chars, seen = [], [], set()
    for c in CHARACTERS:
        prefix = GROUPS[c["group"]][0]
        base = f"SK_{prefix}_{pascal(c['key'].replace('_', ' ')) if c['key'] else pascal(c['name'])}"
        tier = TIERS[c["tier"]]
        bones = SK.build_skeleton(c["skeleton"])
        assets = []

        def add(name, kind, label, tris, notes="", count=1):
            if name in seen:
                problems.append(f"Duplicate asset {name}")
            seen.add(name)
            assets.append(OrderedDict(asset=name, kind=kind, label=label, lod_tris=lods(tris), count=count, notes=notes,
                                      blend_path=f"assets/characters/{GROUPS[c['group']][2][3:-3]}/{name.replace('_##', '')}.blend"))

        add(base, "Base", "Base body + head (default outfit and hair for budget checks)", tier["tris"],
            "Includes head, body skin and the default outfit and hair when checking the full-character budget.")
        body_budget = tier["split"].get("Body + outfit") or tier["split"].get("Body") or tier["tris"]
        hair_budget = tier["split"].get("Hair", 0)
        for o in c["outfits"]:
            if o["shared"]:
                continue
            if o["key"] == "Modules":
                for piece in o["pieces"]:
                    m = re.match(r"(.+?)\s*×\s*(\d+)", piece)
                    fam, n = (m.group(1), int(m.group(2))) if m else (piece, 1)
                    share = next((v for k, v in MODULE_SHARE if k in fam.lower()), 0.08)
                    if share == 0:
                        add(f"T_CRE_{pascal(c['key'] or c['name'])}_{pascal(fam)}_##", "Kit texture", f"{fam} (×{n}, 2K masks, no mesh)", 0, count=n)
                    else:
                        add(f"{base}_{pascal(fam)}_##", "Kit module", f"{fam} (×{n})", int(tier["tris"] * share), count=n)
                continue
            if o["key"] in NON_ASSET_OUTFITS:
                continue
            add(f"{base}_Outfit_{o['key']}", "Outfit", o["name"], body_budget, o["acts"])
        for key, label, kind in c["hair"]:
            if key == "Library":
                continue
            add(f"{base}_Hair_{key}", "Hair", f"{label} ({kind})", hair_budget or 4000)
        for vkey, vdesc in c["variants"]:
            add(f"{base}_{pascal(vkey)}", "Variant", vdesc, tier["tris"])
        if c["arms_1p"]:
            for o in c["outfits"]:
                if not o["shared"]:
                    add(f"{base}_Arms1P_{o['key']}", "1P arms", f"First-person arms — {o['name']}", 25000)
        facial = SK.FACIAL_SETS[tier["facial"]]
        if c["group"] == "HOL" and c["name"] == "Mimic":
            facial = SK.FACIAL_SETS["secondary"]
        humanoid = c["skeleton"]["template"] == "humanoid"
        entry = OrderedDict(
            id=c["id"], group=c["group"], group_name=GROUPS[c["group"]][1], key=c["key"] or snake(c["name"]),
            registry_id=f"char.{c['group'].lower()}.{c['key'] or snake(c['name'])}", name=c["name"], title=c["title"],
            tier=c["tier"], age=c["age"], pronouns=c["pronouns"], role=c["role"], appears=c["appears"], story=c["story"],
            voice=c["voice"], visual=c["visual"], outfits=c["outfits"], hair=c["hair"], variants=c["variants"],
            skeleton=c["skeleton"], skeleton_label=skeleton_label(c["skeleton"]), size_label=size_label(c["skeleton"]),
            bone_count=len(bones), deform_bones=sum(1 for b in bones if b["deform"]), extra_bones=c["extra_bones"],
            facial_set=tier["facial"] if not (c["group"] == "HOL" and c["name"] == "Mimic") else "secondary",
            facial_shapes=len(facial), extra_shapes=c["extra_shapes"],
            infection=c["infection"] and humanoid and c["tier"] not in ("Enemy", "Elite", "Boss", "Hologram"),
            facial_capture=c["facial_capture"], mocap=c["mocap"], cloth=c["cloth"], notes=c["notes"], gameplay=c["gameplay"],
            customization=c["customization"], arms_1p=c["arms_1p"], art_set=c["art"],
            sockets=([s[0] for s in SK.HUMANOID_SOCKETS] if humanoid else []) + [s for s in c["sockets"] if not s.split(" ")[0] in {x[0] for x in SK.HUMANOID_SOCKETS}],
            textures=tier["textures"], influences=tier["influences"], hair_spec=tier["hair"], budget_split=tier["split"],
            assets=assets,
        )
        chars.append(entry)
    return chars, problems


# --------------------------------------------------------------------------- markdown helpers
def swatches(palette):
    return " · ".join(f"{n} `{h}`" for n, h in palette)


GAMEPLAY_LABELS = {"hp": "HP", "speed_mps": "Speed (m/s)", "damage": "Damage", "infection_per_hit": "Infection / hit",
                   "counter": "Counter", "weapons": "Weapons", "behaviour": "Behavior", "phases": "Phases",
                   "talk_down": "Talk-down", "summons": "Summons", "attacks": "Attacks"}
MODULE_SHARE = [("pattern", 0.0), ("bod", 0.45), ("head", 0.2), ("leg", 0.2), ("wing", 0.15), ("tail", 0.1)]

VISUAL_LABELS = [("silhouette", "Silhouette"), ("face", "Face"), ("hair", "Hair"), ("body", "Body"), ("marks", "Marks"),
                 ("bloom", "Bloom growth"), ("weak_points", "Weak points"), ("phases", "Phases"), ("environment", "Environment"),
                 ("faction", "Faction"), ("face_visible", "Face visible"), ("fur", "Fur / feathers"),
                 ("props", "Signature props"), ("acting", "Acting & movement"), ("audio", "Audio")]


def visual_block(v):
    lines = []
    for key, label in VISUAL_LABELS:
        if v.get(key):
            val = v[key]
            if isinstance(val, list):
                val = "; ".join(val)
            lines.append(f"- **{label}:** {esc(val)}")
    if v.get("palette"):
        lines.append(f"- **Palette:** {swatches(v['palette'])}")
    return lines


def card(c, full=True):
    L = []
    title = f"### {c['id']} · {c['name']}" + (f" — *{c['title']}*" if c["title"] else "")
    L += [title, ""]
    meta = [f"`{c['registry_id']}`", f"**Tier** {c['tier']}", f"**Size** {c['size_label']}"]
    if c["age"] and c["age"] != "—":
        meta.append(f"**Age** {c['age']}")
    if c["pronouns"] and c["pronouns"] != "—":
        meta.append(f"**Pronouns** {c['pronouns']}")
    L += [" · ".join(meta), ""]
    if c["role"]:
        L += [f"> {esc(c['role'])}", ""]
    if c["appears"]:
        L += [f"**Appears:** {esc(c['appears'])}", ""]

    s = c["story"]
    if any(s.get(k) for k in ("want", "need", "wound", "lie")):
        L += ["**Story**", "", "| Want | Need | Wound | Lie |", "|---|---|---|---|",
              f"| {esc(s.get('want', '—'))} | {esc(s.get('need', '—'))} | {esc(s.get('wound', '—'))} | {esc(s.get('lie', '—'))} |", ""]
    if s.get("arc"):
        L += [f"**Arc:** {esc(s['arc'])}", ""]
    if c["voice"]:
        L += [f"**Voice & performance:** {esc(c['voice'])}", ""]

    gp = {k: v for k, v in c["gameplay"].items() if k != "role"}
    if gp:
        L += ["**Gameplay**", "", "| " + " | ".join(GAMEPLAY_LABELS.get(k, k.replace("_", " ").capitalize()) for k in gp) + " |",
              "|" + "---|" * len(gp), "| " + " | ".join(esc(v) for v in gp.values()) + " |", ""]

    vb = visual_block(c["visual"])
    if vb:
        L += ["**Visual design**", ""] + vb + [""]

    if c["customization"]:
        L += ["**Character creator**", "", "| Area | Options |", "|---|---|"]
        for k, v in c["customization"].items():
            L.append(f"| {k} | {esc(v)} |")
        L.append("")

    if c["outfits"]:
        L += ["**Wardrobe**", "", "| Outfit | When | Description | Pieces | Asset |", "|---|---|---|---|---|"]
        base = c["assets"][0]["asset"]
        for o in c["outfits"]:
            if o["shared"]:
                asset = f"`{o['shared']}` (shared suit)"
            elif o["key"] in NON_ASSET_OUTFITS:
                asset = "— (conversion / built from kits)"
            elif o["key"] == "Modules":
                asset = f"`{base}_<Module>_##`"
            else:
                asset = f"`{base}_Outfit_{o['key']}`"
            L.append(f"| **{esc(o['name'])}** | {esc(o['acts'])} | {esc(o['desc'])} | {esc(', '.join(o['pieces'])) or '—'} | {asset} |")
        L.append("")

    # Blender spec
    L += ["**Blender assets**", "", "| Asset | Type | Contents | LOD0 / 1 / 2 / 3 tris |", "|---|---|---|---|"]
    for a in c["assets"]:
        count = f" ×{a['count']}" if a["count"] > 1 else ""
        L.append(f"| `{a['asset']}`{count} | {a['kind']} | {esc(a['label'])} | {' / '.join(fmt(t) for t in a['lod_tris'])} |")
    L.append("")
    split = " · ".join(f"{k} {fmt(v)}" for k, v in c["budget_split"].items())
    L += ["**Blender spec**", ""]
    L.append(f"- **Skeleton:** {c['skeleton_label']} · {c['bone_count']} bones ({c['deform_bones']} deform)"
             + (f" · extra bones: {esc('; '.join(c['extra_bones']))}" if c["extra_bones"] else ""))
    L.append(f"- **Budget (LOD0 {fmt(TIERS[c['tier']]['tris'])} tris):** {split}")
    L.append(f"- **Textures:** {c['textures']}")
    shapes = f"{c['facial_set']} set ({c['facial_shapes']} shape keys, see chapter 10)"
    if c["extra_shapes"]:
        shapes += f" + {esc(', '.join(c['extra_shapes']))}"
    L.append(f"- **Facial rig:** {shapes}" + (" · **facial capture**" if c["facial_capture"] else ""))
    if c["infection"]:
        L.append("- **Infection states:** Stage 0–4 via `INF_` shape keys + infection masks (chapter 00 §0.10)")
    L.append(f"- **Skin weights:** max {c['influences']} influences per vertex")
    L.append(f"- **Hair:** {c['hair_spec']}" + (f" · {esc('; '.join(f'{h[1]} ({h[2]})' for h in c['hair']))}" if c["hair"] else ""))
    if c["cloth"]:
        L.append(f"- **Cloth / physics:** {esc(', '.join(c['cloth']))}")
    if c["sockets"]:
        L.append(f"- **Sockets:** " + ", ".join(f"`{s.split(' ')[0]}`" for s in c["sockets"]))
    if c["mocap"]:
        L.append(f"- **Capture:** {esc(c['mocap'])}")
    if c["notes"]:
        L.append(f"- **Notes:** {esc(c['notes'])}")
    L.append(f"- **Files:** `{c['assets'][0]['blend_path']}` (one .blend per asset)")
    L.append("")
    return "\n".join(L)


def group_doc(code, chars, intro, extra=""):
    _prefix, title, doc = GROUPS[code]
    number = doc.split("-", 1)[0]
    cs = [c for c in chars if c["group"] == code]
    n_assets = sum(a["count"] for c in cs for a in c["assets"] if a["kind"] != "Kit texture")
    L = [GENERATED_NOTE, f"# {number} — {title}", "", intro, "",
         f"**{len(cs)} entries · {n_assets} Blender assets.** Standards: [00 — Character Art & Blender Standards](00-character-art-standards.md) · "
         f"skeletons and facial sets: [10 — Skeletons, Rigging & Facial](10-skeletons-rigging-and-facial.md).", ""]
    L += ["## Contents", "", "| ID | Name | Tier | Size | Assets |", "|---|---|---|---|---|"]
    for c in cs:
        anchor = re.sub(r"[^a-z0-9 -]", "", f"{c['id']} · {c['name']}" .lower() + (f" — {c['title']}".lower() if c["title"] else "")).replace(" ", "-")
        L.append(f"| {c['id']} | [{c['name']}](#{anchor}) | {c['tier']} | {c['size_label']} | {sum(a['count'] for a in c['assets'] if a['kind'] != 'Kit texture')} |")
    L += ["", extra, "---", ""] if extra else ["", "---", ""]
    for c in cs:
        L += [card(c), "---", ""]
    return "\n".join(L)


INTROS = {
    "PLY": "Wrench, the player: a fully customizable Hero-tier character seen in first person nearly all the time, in third person optionally, and in every in-engine scene and cinematic. First-person arms are separate assets per outfit.",
    "CST": "Companions, antagonists and story NPCs. Every story character is performance-captured. Family likeness (Wrench and Ada) and continuity across boss forms (Crane) are built into shared head topology.",
    "NOT": "The 12 fully voiced notable survivors, each with a personal quest. They are Secondary tier: unique head, hair and signature outfit on shared kit bodies. The 28 text-and-bark notables follow as a table.",
    "HOL": "The Hollow bestiary and the Sower constructs. **Style rules:** horror through wrongness, not gore; Bloom growth replaces blood; bodies burst into spores, not viscera. Hollows are *converted* from survivor-kit bodies, so any adult body and outfit combination can become a Hollow. **There are no child Hollows** (game bible 17 §17.8).",
    "FAC": "Human (and drone) units of the Ark Directorate, the Choir and the Free Haulers. Helmeted units use Crowd-tier budgets; units whose faces are seen in dialogue are Secondary tier.",
    "BOS": "Boss forms. Each boss reuses its story character's head topology so phase transitions and talk-downs stay in close-up.",
    "CRE": "Creatures and fauna: the Tessari, Earth wildlife, the procedural Drift fauna kits, and the creatures of the Seedship's memory gardens.",
}


def overview_doc(chars):
    L = [GENERATED_NOTE, "# 01 — Cast Overview", "",
         f"Every character, creature and enemy in EXODUS PROTOCOL: **{len(chars)} entries**, "
         f"**{sum(a['count'] for c in chars for a in c['assets'] if a['kind'] != 'Kit texture')} Blender assets**, plus {len(MORE_SURVIVORS)} kit-built notable survivors "
         "and the procedural survivor kit.", ""]
    img = OUT / "images" / "cast-lineup.jpg"
    if img.exists():
        L += ["![Height lineup of the main cast, generated by the Blender character toolkit](images/cast-lineup.jpg)", "",
              "*Height lineup: stand-in bodies generated by `tools/blender/exodus_characters.py` from each character's skeleton and height.*", ""]
    img = OUT / "images" / "scale-chart.jpg"
    if img.exists():
        L += ["![Scale chart of the player beside enemies, bosses and creatures](images/scale-chart.jpg)", "",
              "*Scale chart: the player beside a Shambler, a Brute, a Directorate Enforcer, a Sower Warden, the Seraph exo-frame and the Tessari (side view). Same toolkit stand-ins.*", ""]
    L += ["## Budget tiers", "", "| Tier | LOD0 tris | Split | Textures | Facial set | Max influences |", "|---|---|---|---|---|---|"]
    for name, t in TIERS.items():
        split = " · ".join(f"{k} {fmt(v)}" for k, v in t["split"].items())
        L.append(f"| **{name}** | {fmt(t['tris'])} | {split} | {t['textures']} | {t['facial']} ({len(SK.FACIAL_SETS[t['facial']])}) | {t['influences']} |")
    L += ["", f"LOD chain: {' / '.join(f'{int(r * 100)}%' for r in LOD_RATIOS)} of LOD0.", ""]
    for code, (_p, title, doc) in GROUPS.items():
        cs = [c for c in chars if c["group"] == code]
        L += [f"## {code} — {title}", "", f"Chapter: [{doc}]({doc})", "",
              "| ID | Name | Role | Tier | Size | Skeleton | Assets |", "|---|---|---|---|---|---|---|"]
        for c in cs:
            role = c["title"] or (c["role"][:70] + "…" if len(c["role"]) > 70 else c["role"])
            L.append(f"| {c['id']} | **{c['name']}** | {esc(role)} | {c['tier']} | {c['size_label']} | {c['skeleton_label']} | {sum(a['count'] for a in c['assets'] if a['kind'] != 'Kit texture')} |")
        L.append("")
    humans = sorted([c for c in chars if c["group"] in ("PLY", "CST", "NOT") and c["skeleton"]["template"] == "humanoid"],
                    key=lambda c: -c["skeleton"]["height"])
    L += ["## Height chart (humanoid cast)", "", "| Name | Height | Proportions |", "|---|---|---|"]
    for c in humans:
        L.append(f"| {c['name']} | {c['skeleton']['height']:.2f} m | {SK.PROFILES[c['skeleton']['profile']]['label']} |")
    L.append("")
    return "\n".join(L)


def notables_extra():
    L = ["## The 28 text-and-bark notable survivors", "",
         "Built from the survivor kit (chapter 05) plus **one unique signature piece each** (`SK_NPC_<Name>_Signature`, 8k tris, 1K texture) "
         "and a chosen head from the 48-head library. Each has a short personal quest delivered through text and barks.", "",
         "| # | Name | Age | Pronouns | Occupation | Found | Traits | Look (signature piece in bold) | Body preset |", "|---|---|---|---|---|---|---|---|---|"]
    for i, (name, age, pron, job, where, traits, look, preset) in enumerate(MORE_SURVIVORS, 13):
        first, _, rest = look.partition(", ")
        L.append(f"| {i} | {name} | {age} | {pron} | {job} | {where} | {traits} | **{first}**{', ' + rest if rest else ''} | {SK.PROFILES[preset]['label']} |")
    L.append("")
    return "\n".join(L)


def kit_doc():
    total = 0
    L = [GENERATED_NOTE, "# 05 — Procedural Survivors (Kit)", "",
         "Everyone in the colony who isn't a story character or a notable is assembled from this modular kit at runtime "
         "(game bible 07 — Colony Life-Sim). Every kit piece is skinned to **EXO_Humanoid** and deforms across the full height and build range "
         "via shared body morph targets. Budgets: Crowd tier (30k LOD0 per assembled survivor), max 4 influences.", "",
         "**Assembly:** body preset → head (+ face morphs, skin tone) → hair / facial hair / headwear → outfit pieces by origin → accessories and marks → infection state.", ""]
    for section, rows in SURVIVOR_KIT.items():
        L += [f"## {section}", "", "| Piece | Description | Count | Asset pattern |", "|---|---|---|---|"]
        for name, desc, count, pattern in rows:
            L.append(f"| {name} | {esc(desc)} | {count} | `{pattern}` |")
            total += count if pattern.startswith("SK_") or pattern.startswith("SM_") else 0
        L.append("")
    L += ["## Rules", "",
          "1. **Layering order:** skin → underlayer → top → outerwear → gear. Each layer hides the faces beneath it (hidden-face masks per piece) so layers never clip.",
          "2. **One skeleton, one set of morphs.** Pieces are weighted to EXO_Humanoid and carry the same body morph targets (`body_slim`, `body_athletic`, `body_broad`, `body_heavy`, `age_older`).",
          "3. **Palette-driven variety:** every outfit piece has 3 color masks recolored at runtime from the survivor's origin palette.",
          "4. **Diversity by design:** the 48 heads, 40 hairstyles and 18 headwear pieces are reviewed together to cover a wide range of ancestries, ages and body types, without caricature.",
          "5. **Child bodies** only use child-safe outfit pieces and never receive injury or infection states beyond Stage 1.",
          "6. **Hollow conversion:** any adult kit survivor can be converted to a Hollow (chapter 06) by swapping to the Hollow material and adding Bloom attachments.",
          "", f"**Kit asset total:** {total} unique meshes.", ""]
    return "\n".join(L), total


def skeleton_doc():
    L = [GENERATED_NOTE, "# 10 — Skeletons, Rigging & Facial", "",
         "Skeleton templates, sockets and facial shape-key sets. They're defined once in `tools/characters/skeletons.py`, "
         "which both this chapter and the Blender toolkit read.", "",
         "**Conventions:** characters **face −Y**, up is +Z, the character's **left is +X** (Blender/Rigify convention; note that building parts use front = +X). "
         "Rest pose is **A-pose** (arms 45° down). Bone names follow the UE5 mannequin so animations retarget directly.", "",
         "## Templates", "", "| Template | Used for | Bones (reference size) |", "|---|---|---|"]
    ref = {
        "humanoid": ({"template": "humanoid", "height": 1.8}, "All people, Hollows, Wardens, exo-frames, Sower Echo"),
        "quadruped": ({"template": "quadruped", "shoulder_h": 1.0, "length": 2.0}, "Dogs, coyotes, horses, Permian fauna, grazer and predator kits"),
        "hexapod": ({"template": "hexapod", "shoulder_h": 1.0, "length": 2.0}, "Tessari, hexapod kit"),
        "flyer": ({"template": "flyer", "shoulder_h": 0.3, "length": 0.6, "wings": 0.6}, "Crows, Hive Mites, flyer kit"),
        "serpentine": ({"template": "serpentine", "length": 3.0}, "Burrower kit"),
        "cetacean": ({"template": "cetacean", "length": 20.0, "girth": 5.0}, "Drowned Choir Singer"),
        "drone": ({"template": "drone", "size": 0.8}, "Sentinel drones (and colony drones in the parts bible)"),
        "hologram": ({"template": "hologram", "height": 1.2}, "KESTREL"),
    }
    for t, (spec, used) in ref.items():
        L.append(f"| **{SK.TEMPLATE_NAMES[t]}** | {used} | {len(SK.build_skeleton(spec))} |")
    L += ["", "## Proportion profiles (humanoid)", "", "| Profile | Width | Head size | Proxy bulk | Description |", "|---|---|---|---|---|"]
    for k, p in SK.PROFILES.items():
        L.append(f"| `{k}` | {p['width']:.2f} | {p['head']:.2f} | {p['bulk']:.2f} | {p['label']} |")
    L += ["", "The skeleton is scaled so the crown of the head lands exactly at the character's height; the head profile scales the head about the neck base.", "",
          "## EXO_Humanoid bone list (1.80 m reference, A-pose)", "", "| Bone | Parent | Deform | Group | Head position (x, y, z) m |", "|---|---|---|---|---|"]
    for b in SK.humanoid(1.8):
        L.append(f"| `{b['name']}` | {('`' + b['parent'] + '`') if b['parent'] else '—'} | {'yes' if b['deform'] else 'no'} | {b['group']} | "
                 f"{b['head'][0]:.3f}, {b['head'][1]:.3f}, {b['head'][2]:.3f} |")
    L += ["", "## Humanoid sockets", "", "| Socket | Bone | Purpose |", "|---|---|---|"]
    for name, bone, _off, purpose in SK.HUMANOID_SOCKETS:
        L.append(f"| `{name}` | `{bone}` | {purpose} |")
    L += ["", "Sockets are empties parented to their bone in Blender and are exported to the `.meta.json` sidecar; the engine creates skeletal-mesh sockets from it.", "",
          "## Facial shape-key sets", "", "| Set | Used by tier | Count | Contents |", "|---|---|---|---|",
          f"| `hero` | Hero, Boss | {len(SK.FACIAL_SETS['hero'])} | ARKit 52 + 24 EXODUS correctives + 4 infection |",
          f"| `main` | Main | {len(SK.FACIAL_SETS['main'])} | ARKit 52 + 12 EXODUS correctives + 4 infection |",
          f"| `secondary` | Secondary (and the Mimic) | {len(SK.FACIAL_SETS['secondary'])} | ARKit 52 + 4 infection |",
          f"| `crowd` | Crowd | {len(SK.FACIAL_SETS['crowd'])} | 24 core expressions + 4 infection |",
          f"| `hollow` | Enemy, Elite | {len(SK.FACIAL_SETS['hollow'])} | Hollow set |",
          f"| `creature` | Creatures | {len(SK.FACIAL_SETS['creature'])} | Creature set |", "",
          "### ARKit 52 (exact names, required for live facial capture)", "", ", ".join(f"`{s}`" for s in SK.ARKIT_52), "",
          "### EXODUS correctives", "", ", ".join(f"`{s}`" for s in SK.EXO_CORRECTIVES), "",
          "### Infection shapes (Stage 0–4)", "",
          "| Shape key | Stage 1 Exposed | Stage 2 Seeded | Stage 3 Blooming | Stage 4 Turning |", "|---|---|---|---|---|",
          "| `INF_Veins` | 0.1 | 0.5 | 0.9 | 1.0 |", "| `INF_Lichen` | 0 | 0.1 | 0.6 | 1.0 |", "| `INF_EyeCloud` | 0 | 0.2 | 0.6 | 1.0 |", "| `INF_GumRecede` | 0 | 0 | 0.4 | 1.0 |", "",
          "Masks (`T_<Char>_InfectionMask`, UV1) drive the matching color changes; shapes add the raised veins and lichen.", "",
          "### Hollow set", "", ", ".join(f"`{s}`" for s in SK.HOLLOW_SHAPES), "",
          "### Crowd set", "", ", ".join(f"`{s}`" for s in SK.CROWD_24), "",
          "### Creature set", "", ", ".join(f"`{s}`" for s in SK.FACIAL_SETS["creature"]), "",
          "## Rigging rules", "",
          "1. **Deform bones only** carry weights; `ik_*` bones are non-deform but exported (UE5 compatibility).",
          "2. **Max influences:** 8 for Hero/Main/Secondary/Boss, 4 for Crowd, enemies and creatures. Weights normalized.",
          "3. **Twist bones** carry 50% of the forearm and upper-arm roll; never weight the hand to the lowerarm twist.",
          "4. **Facial motion** is shape keys plus `jaw` and `eye_l/r` bones; no other facial bones in the shipping skeleton.",
          "5. **Extra bones** (Bloom attach, jiggle sacs, prosthetic fingers, armor plates) are children of standard bones, named in lowercase with a clear prefix (`bloom_`, `sac_`, `plate_`, `claw_`, `tendril_`), so animation retargeting ignores them.",
          "6. **Outfits and hair** are separate skinned meshes on the same armature; each has its own LODs.",
          ""]
    return "\n".join(L)


def portraits_extra():
    L = ["## Portrait-only characters", "", "Seen only in photos, logs and memorials (2D portraits, painted from a scanned stand-in and a short photo shoot).", "",
         "| Name | Where they appear |", "|---|---|"]
    for n, d in PORTRAITS:
        L.append(f"| {n} | {esc(d)} |")
    L.append("")
    return "\n".join(L)


# --------------------------------------------------------------------------- data
def write_data(chars, kit_total):
    DATA.mkdir(parents=True, exist_ok=True)
    (DATA / "characters.json").write_text(json.dumps(OrderedDict(
        schema="exodus.characters/1", tiers=TIERS, lod_ratios=LOD_RATIOS, groups={k: {"prefix": v[0], "title": v[1], "doc": v[2]} for k, v in GROUPS.items()},
        characters=chars, more_survivors=[dict(zip(["name", "age", "pronouns", "job", "found", "traits", "look", "preset"], r)) for r in MORE_SURVIVORS],
        survivor_kit=SURVIVOR_KIT, portraits=[{"name": n, "note": d} for n, d in PORTRAITS]), indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    skel = {"profiles": SK.PROFILES, "humanoid_sockets": [dict(zip(["name", "bone", "offset", "purpose"], s)) for s in SK.HUMANOID_SOCKETS],
            "facial_sets": SK.FACIAL_SETS, "humanoid_reference": SK.humanoid(1.8)}
    (DATA / "skeletons.json").write_text(json.dumps(skel, indent=1) + "\n", encoding="utf-8")
    with open(DATA / "art_tracker_characters.csv", "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["asset", "count", "character_id", "character", "group", "type", "contents", "tier", "skeleton", "size",
                    "lod0_tris", "lod1_tris", "lod2_tris", "lod3_tris", "textures", "facial_set", "facial_capture", "blend_path", "status", "owner", "notes"])
        for c in chars:
            for a in c["assets"]:
                w.writerow([a["asset"], a["count"], c["id"], c["name"], c["group"], a["kind"], a["label"], c["tier"], c["skeleton_label"],
                            c["size_label"], *a["lod_tris"], c["textures"], c["facial_set"], "yes" if c["facial_capture"] else "no",
                            a["blend_path"], "Not started", "", a["notes"]])
        for name, age, pron, job, where, traits, look, preset in MORE_SURVIVORS:
            w.writerow([f"SK_NPC_{pascal(name)}_Signature", 1, "NOT-kit", name, "NOT", "Signature piece", look.split(",")[0], "Crowd",
                        "EXO_Humanoid", preset, 8000, 4000, 1600, 480, "1K", "crowd", "no",
                        f"assets/characters/notable-survivors/SK_NPC_{pascal(name)}_Signature.blend", "Not started", "", job])


def update_readme(chars, kit_total):
    readme = OUT / "README.md"
    if not readme.exists():
        return
    text = readme.read_text(encoding="utf-8")
    start, end = "<!-- STATS:START -->", "<!-- STATS:END -->"
    if start not in text:
        return
    n_assets = sum(a["count"] for c in chars for a in c["assets"] if a["kind"] != "Kit texture")
    rows = [start, "| | Count |", "|---|---|"]
    for code, (_p, title, _d) in GROUPS.items():
        cs = [c for c in chars if c["group"] == code]
        rows.append(f"| {title} | {len(cs)} {'entry' if len(cs) == 1 else 'entries'} · {sum(a['count'] for c in cs for a in c['assets'] if a['kind'] != 'Kit texture')} assets |")
    rows += [f"| Text-and-bark notables (kit-built) | {len(MORE_SURVIVORS)} (one signature piece each) |",
             f"| Procedural survivor kit | {kit_total} kit meshes |",
             f"| **Total Blender assets** | **{n_assets + len(MORE_SURVIVORS) + kit_total}** |", end]
    text = text[: text.index(start)] + "\n".join(rows) + text[text.index(end) + len(end):]
    readme.write_text(text, encoding="utf-8")


def main():
    chars, problems = expand()
    if problems:
        print("\n".join(problems))
        sys.exit(1)
    if "--check" in sys.argv:
        print(f"OK: {len(chars)} characters, {sum(a['count'] for c in chars for a in c['assets'] if a['kind'] != 'Kit texture')} assets")
        return
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "01-cast-overview.md").write_text(overview_doc(chars) + "\n", encoding="utf-8")
    for code in GROUPS:
        extra = notables_extra() if code == "NOT" else (portraits_extra() if code == "CST" else "")
        (OUT / GROUPS[code][2]).write_text(group_doc(code, chars, INTROS[code], extra) + "\n", encoding="utf-8")
    kit_md, kit_total = kit_doc()
    (OUT / "05-procedural-survivors.md").write_text(kit_md + "\n", encoding="utf-8")
    (OUT / "10-skeletons-rigging-and-facial.md").write_text(skeleton_doc() + "\n", encoding="utf-8")
    write_data(chars, kit_total)
    update_readme(chars, kit_total)
    print(f"Built {len(chars)} characters, {sum(a['count'] for c in chars for a in c['assets'] if a['kind'] != 'Kit texture')} assets "
          f"(+{len(MORE_SURVIVORS)} signature pieces, {kit_total} kit meshes) -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
