#!/usr/bin/env python3
"""Build the EXODUS PROTOCOL Level Design Bible from the level catalog.

    python3 tools/levels/build.py           # regenerate chapters, JSON and CSV
    python3 tools/levels/build.py --check   # validate only

Generated (docs/level-bible/): 01–10 chapters, data/levels.json, data/level_tracker.csv,
data/kit_tracker.csv. Chapters 00, 11–14 and the README are hand-written; the README
stats block is refreshed here.
"""

import csv
import json
import math
import re
import sys
from collections import OrderedDict
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
OUT = ROOT / "docs" / "level-bible"
DATA = OUT / "data"
sys.path.insert(0, str(HERE))

from catalog import (FLIGHT, GROUPS, GYM, JUMP, KITS, LEVELS, MARKER_PREFIXES, METRICS, NAV_AGENTS, PLANET_STANDARD,  # noqa: E402
                     PULSE, STATIONS, THRESHOLDS, TYPES)
from catalog.planets import OTHER_BODIES, SYSTEM_SCALE  # noqa: E402

GENERATED_NOTE = "<!-- GENERATED by tools/levels/build.py from tools/levels/catalog/. Do not edit by hand. -->"
SPEEDS = {"walk": 1.6, "sprint": 6.2, "rover": 25.0}


def pascal(t):
    t = t.replace("×", "x").replace("&", "And").replace("'", "").replace("’", "").replace("—", " ")
    return "".join(p[:1].upper() + p[1:] for p in re.split(r"[^0-9A-Za-z]+", t) if p)


def snake(t):
    return re.sub(r"[^0-9a-z]+", "_", t.lower().replace("'", "").replace("’", "")).strip("_")


def esc(t):
    return str(t).replace("|", "\\|")


def fmt(n, d=0):
    if isinstance(n, float) and d:
        return f"{n:,.{d}f}"
    return f"{int(round(n)):,}"


def fmt_m(m):
    return f"{m / 1000:,.1f} km" if m >= 10000 else f"{m:,.0f} m"


def fmt_dur(seconds):
    h = seconds / 3600
    if seconds < 120:
        return f"{seconds:,.0f} s"
    return f"{h:,.1f} h" if h >= 1 else f"{seconds / 60:,.0f} min"


# --------------------------------------------------------------------------- planet maths
def transition_numbers(diameter_km, airless):
    R = diameter_km * 500.0
    atm = 0.0 if airless else PLANET_STANDARD["atmosphere_height_frac"] * R
    approach = THRESHOLDS["airless_approach_frac"] * R if airless else atm
    cap = FLIGHT["airless_approach_cap_mps"] if airless else FLIGHT["atmo_cruise_mps"][1]
    dropout = THRESHOLDS["pulse_dropout_frac"] * R
    dive = approach / math.sin(math.radians(FLIGHT["dive_angle_deg"]))
    t = (dropout - approach) / FLIGHT["space_cruise_mps"] + dive / cap + FLIGHT["auto_land_s"]
    return OrderedDict(airless=airless, atmosphere_top_m=atm, approach_altitude_m=approach, speed_cap_mps=cap,
                       cloud_deck_m=0.0 if airless else THRESHOLDS["cloud_layer_frac_of_atmo"] * atm, pulse_dropout_m=dropout,
                       streaming_start_m=THRESHOLDS["streaming_start_frac"] * R, capital_parking_m=approach + THRESHOLDS["orbit_parking_frac"] * R,
                       orbit_to_ground_s=t)


def planet_numbers(diameter_km):
    std = PLANET_STANDARD
    R = diameter_km * 500.0  # metres
    eye = std["eye_height_m"]
    horizon = math.sqrt(2 * R * eye)

    def landmark_height(d):
        return 0.0 if d <= horizon else (d - horizon) ** 2 / (2 * R)

    px = max(v for k, v in std["cube_face_heightmap_px"].items() if k <= max(diameter_km, 20))
    face_arc = math.pi * R / 2
    return OrderedDict(
        diameter_km=diameter_km, radius_km=R / 1000, circumference_km=math.pi * diameter_km, surface_area_km2=4 * math.pi * (R / 1000) ** 2,
        atmosphere_height_m=std["atmosphere_height_frac"] * R, crust_depth_m=std["crust_depth_frac"] * R,
        max_elevation_m=std["max_elevation_frac"] * R, gravity_zero_altitude_m=(std["gravity_zero_frac"] - 1) * R,
        horizon_m=horizon, landmark_500m=landmark_height(500), landmark_1km=landmark_height(1000), landmark_2km=landmark_height(2000),
        landmark_5km=landmark_height(5000), drop_1km=1000 ** 2 / (8 * R), drop_8km=8000 ** 2 / (8 * R), drop_16km=16000 ** 2 / (8 * R),
        face_px=px, face_m_per_px=face_arc / px,
        walk_equator_s=math.pi * diameter_km * 1000 / SPEEDS["walk"], sprint_equator_s=math.pi * diameter_km * 1000 / SPEEDS["sprint"],
        rover_equator_s=math.pi * diameter_km * 1000 / SPEEDS["rover"])


# --------------------------------------------------------------------------- expand
def expand():
    problems, levels, ids = [], [], {}
    kit_codes = {k["code"] for k in KITS}
    for lv in LEVELS:
        folder = GROUPS[lv["group"]][1][3:-3]
        name_key = lv["key"] or snake(lv["name"])
        asset = f"LVL_{lv['id'].replace('-', '_')}_{pascal(lv['name'])}"
        t = TYPES[lv["type"]]
        size = lv["size"]
        budget = OrderedDict(t)
        if t.get("per") == "cell":
            cells = math.ceil(size["w"] / t["cell_m"]) * math.ceil(size["d"] / t["cell_m"])
            budget["cells"] = cells
        for k in lv["kits"]:
            if k not in kit_codes:
                problems.append(f"{lv['id']}: unknown kit {k}")
        for m in lv["markers"]:
            if not m.startswith(tuple(MARKER_PREFIXES)):
                problems.append(f"{lv['id']}: marker {m} has no approved prefix")
        for sp in lv["spaces"]:  # spaces must fit the level footprint (the Blender validator checks the 3D bounds)
            w, d = sp["size"][0], sp["size"][1]
            if sp["pos"]:
                x, y = sp["pos"][0], sp["pos"][1]
                if abs(x) + w / 2 > size["w"] / 2 + 1 or abs(y) + d / 2 > size["d"] / 2 + 1:
                    problems.append(f"{lv['id']}: space '{sp['name']}' extends outside the {size['w']:g} × {size['d']:g} m footprint")
            elif w > size["w"] + 1 or d > size["d"] + 1:
                problems.append(f"{lv['id']}: space '{sp['name']}' is larger than the level")
        for c in lv["connections"]:
            names = {s["name"] for s in lv["spaces"]}
            if lv["type"] not in ("Open Region",) and (c[0] not in names or c[1] not in names):
                problems.append(f"{lv['id']}: connection {c} references an unknown space")
        entry = OrderedDict(lv)
        entry.update(registry_id=f"level.{lv['group'].lower()}.{name_key}", asset=asset,
                     blend_path=f"assets/levels/{folder}/{asset}.blend", export_path=f"export/levels/{folder}/{asset}.fbx", budget=budget)
        if lv["planet"]:
            entry["planet_numbers"] = planet_numbers(lv["planet"]["diameter_km"])
            entry["transition_numbers"] = transition_numbers(lv["planet"]["diameter_km"], lv["planet"]["atmosphere"].startswith("None"))
        levels.append(entry)
        ids[lv["id"]] = entry
    for e in levels:
        op = e.get("on_planet")
        if op and op["planet"] not in ids:
            problems.append(f"{e['id']}: on_planet references unknown {op['planet']}")
        elif op and e["type"] in ("Open Region", "Planet Region"):
            span_km = max(e["size"]["w"], e["size"]["d"]) / 1000
            limit = min(PLANET_STANDARD["region_max_km"], PLANET_STANDARD["region_max_frac_of_diameter"] * ids[op["planet"]]["planet"]["diameter_km"])
            if span_km > limit + 1e-6:
                problems.append(f"{e['id']}: region is {span_km:g} km across; the limit on {op['planet']} is {limit:g} km")
    for k in KITS:
        for piece in k["pieces"]:
            if piece["pivot"] not in ("corner", "bottom-center", "center"):
                problems.append(f"{k['code']}: piece '{piece['name']}' has unknown pivot rule '{piece['pivot']}'")
    return levels, problems


# --------------------------------------------------------------------------- markdown
def swatches(p):
    return " · ".join(f"{n} `{h}`" if h.startswith("#") else n for n, h in p)


def size_label(s):
    lab = f"{fmt_m(s['w'])} × {fmt_m(s['d'])} × {fmt_m(s['h'])}"
    if s.get("area_km2"):
        lab += f" ({s['area_km2']} km²)"
    return lab


def kit_anchor(code):
    k = next(k for k in KITS if k["code"] == code)
    return f"[{code}](10-modular-kits.md#{(code + ' — ' + k['name']).lower().replace(' ', '-').replace('—', '').replace('&', '')})"


def planet_table(e):
    p, n = e["planet"], e["planet_numbers"]
    rows = [("Diameter / radius", f"{p['diameter_km']} km / {n['radius_km']:.0f} km" + (f" (seeded range {p['diameter_range_km'][0]}–{p['diameter_range_km'][1]} km; figures shown for the maximum)" if p.get("diameter_range_km") else "")),
            ("Circumference / surface area", f"{n['circumference_km']:,.0f} km / {n['surface_area_km2']:,.0f} km²"),
            ("Gravity / atmosphere", f"{p['gravity_g']} g / {p['atmosphere']}"),
            ("Atmosphere height", fmt_m(n["atmosphere_height_m"]) + " (atmospheric thrust fades to zero at the top)"),
            ("Gravity well", f"Full gravity to the tallest terrain, then ×(R/r)^{PLANET_STANDARD['gravity_falloff_exponent']}; treated as zero {fmt_m(n['gravity_zero_altitude_m'])} up"),
            ("Terrain elevation range", f"±{fmt_m(n['max_elevation_m'])}"),
            ("Minable voxel crust", f"{fmt_m(n['crust_depth_m'])} deep, then unminable bedrock"),
            ("Horizon at eye height (1.8 m)", fmt_m(n["horizon_m"])),
            ("Landmark height to be seen from 500 m / 1 km / 2 km / 5 km",
             " / ".join("ground level" if v < 0.5 else fmt_m(v) for v in (n["landmark_500m"], n["landmark_1km"], n["landmark_2km"], n["landmark_5km"]))),
            ("Curvature drop over 1 km / 8 km / 16 km", f"{n['drop_1km']:.1f} m / {n['drop_8km']:.0f} m / {n['drop_16km']:.0f} m"),
            ("Cube-face heightmaps", f"6 × {n['face_px']:,}² px, 16-bit ({n['face_m_per_px']:.1f} m/px base; voxel detail and stamps add 1 m detail)"),
            ("Equator on foot / sprinting / by rover", f"{fmt_dur(n['walk_equator_s'])} / {fmt_dur(n['sprint_equator_s'])} / {fmt_dur(n['rover_equator_s'])}"),
            ("Day length", f"{p['day_min']} min"), ("Oceans", "Yes" if p["sea_level"] is True else ("No" if not p["sea_level"] else p["sea_level"])),
            ("Orbit", p["orbit"])]
    tn = e["transition_numbers"]
    rows += [("Pulse-drive dropout (and no-pulse zone)", f"{fmt_m(tn['pulse_dropout_m'])} altitude"),
             ("Atmosphere entry" if not tn["airless"] else "Approach speed cap (airless)",
              f"{fmt_m(tn['approach_altitude_m'])} altitude → speed capped to {tn['speed_cap_mps']} m/s over {FLIGHT['entry_speed_ramp_s']} s"),
             ("Cloud deck", "—" if tn["airless"] else f"{fmt_m(tn['cloud_deck_m'])} altitude"),
             ("Voxel streaming starts (impostor before)", f"{fmt_m(tn['streaming_start_m'])} from the centre"),
             ("Capital ships park at", f"{fmt_m(tn['capital_parking_m'])} altitude"),
             ("Pulse dropout → landed (assisted flight)", fmt_dur(tn["orbit_to_ground_s"]))]
    L = ["**Planet profile**", "", "| | |", "|---|---|"] + [f"| {a} | {esc(b)} |" for a, b in rows] + [""]
    if p.get("size_classes"):
        L += ["**Size classes**", "", "| Class | Diameter | Share |", "|---|---|---|"] + [f"| {a} | {b} | {c} |" for a, b, c in p["size_classes"]] + [""]
    L += [f"**Biomes:** {esc(', '.join(p['biomes']))}", "", "**Ore by depth**", "", "| Depth | Ores |", "|---|---|"]
    L += [f"| {d} | {o} |" for d, o in p["ore_layers"]] + [""]
    if p["anchors"]:
        L += ["**Anchored levels**", "", "| Level | Latitude | Longitude |", "|---|---|---|"] + [f"| {a} | {la:.1f}° | {lo:.1f}° |" for a, la, lo in p["anchors"]] + [""]
    if p.get("notes"):
        L += [f"**Notes:** {esc(p['notes'])}", ""]
    return L


def card(e, levels_by_id):
    L = [f"### {e['id']} · {e['name']}", ""]
    meta = [f"`{e['registry_id']}`", f"**Type** {e['type']}", f"**Act** {e['act']}"]
    if e["missions"]:
        meta.append(f"**Missions** {', '.join(e['missions'])}")
    meta.append(f"**Size** {size_label(e['size'])}")
    if e["playtime"]:
        meta.append(f"**Playtime** {e['playtime']}")
    L += [" · ".join(meta), ""]
    if e.get("on_planet"):
        op = e["on_planet"]
        L += [f"**On planet:** {levels_by_id[op['planet']]['name']} ({op['planet']}) at {op['lat']:.1f}°, {op['lon']:.1f}°", ""]
    if e["pos"] and e["group"] == "KVL":
        L += [f"**Map position:** {e['pos'][0]:+.1f} km east, {e['pos'][1]:+.1f} km north (radius {e['pos'][2]:.2f} km)", ""]
    elif e["pos"]:
        L += [f"**Location in Kestrel Valley:** {e['pos'][0]:+.2f} km east, {e['pos'][1]:+.2f} km north", ""]
    L += [f"> {esc(e['summary'])}", ""]
    if e["planet"]:
        L += planet_table(e)
    if e["goals"]:
        L += ["**Player goals**", ""] + [f"- {esc(g)}" for g in e["goals"]] + [""]
    if e["map"]:
        L += ["**Layout**", "", "```", e["map"].strip("\n"), "```", ""]
    if e["spaces"]:
        L += ["**Spaces**", "", "| Space | Size (W × D × H) | Purpose | Position (x, y, z) |", "|---|---|---|---|"]
        for s in e["spaces"]:
            pos = ", ".join(fmt_m(v) if abs(v) >= 10000 else f"{v:g} m" for v in s["pos"]) if s["pos"] else "auto"
            L.append(f"| **{esc(s['name'])}** | {' × '.join(fmt_m(v) if v >= 10000 else f'{v:g} m' for v in s['size'])} | {esc(s['purpose'])} | {pos} |")
        L.append("")
    if e["connections"]:
        L += ["**Connections:** " + "; ".join(f"{esc(a)} ↔ {esc(b)} ({c})" for a, b, c in e["connections"]), ""]
    for label, key in (("Encounters", "encounters"), ("Set pieces", "setpieces"), ("Landmarks & navigation", "landmarks")):
        if e[key]:
            L += [f"**{label}:** " + esc("; ".join(e[key])), ""]
    env = []
    if e["gravity"]:
        env.append(f"gravity {e['gravity']}")
    if e["atmosphere"]:
        env.append(f"atmosphere {e['atmosphere']}")
    if e["hazards"]:
        env.append(f"hazards: {e['hazards']}")
    if e["bloom"]:
        env.append(f"Bloom {e['bloom']}")
    env.append(f"building: {e['build']}")
    L += ["**Environment:** " + esc("; ".join(env)), ""]
    m = e["mood"]
    if m:
        L += [f"**Mood & lighting:** {esc(m.get('time', ''))}. {esc(m.get('light', ''))}." + (f" Palette: {swatches(m['palette'])}" if m.get("palette") else ""), ""]
    if e["audio"]:
        L += [f"**Audio:** {esc(e['audio'])}", ""]
    if e["links"]:
        L += [f"**Open-world links:** {esc(e['links'])}", ""]
    # Blender spec
    b = e["budget"]
    L += ["**Blender spec**", ""]
    L.append(f"- **File:** `{e['blend_path']}` → `{e['export_path']}` + `.markers.json`")
    if e["type"] == "Planet":
        n = e["planet_numbers"]
        L.append(f"- **Scaffold:** true-scale cube-sphere (radius {n['radius_km']:.0f} km) as six `TER_Face_PX…NZ` objects with per-face UVs; shells `REF_Atmosphere`, `REF_CrustBase`, "
                 f"`REF_GravityWell`{', `REF_SeaLevel`' if e['planet']['sea_level'] else ''}; `LVL_ANCHOR_*` empties on the surface at each anchor's latitude/longitude (Z along the surface normal); orbit camera")
        L.append(f"- **Face-map templates:** heightmap, biome, ore and Bloom maps per face (`<Planet>_<Map>_<Face>.png`), authoring resolution 1,024² → final {n['face_px']:,}² 16-bit")
        L.append(f"- **Voxel settings:** {PLANET_STANDARD['voxel_size_m']} m voxels, {PLANET_STANDARD['voxel_chunk_m']} m chunks, {PLANET_STANDARD['clipmap_lod_rings']} clipmap LOD rings · memory {b['memory_mb']} MB resident")
    elif b.get("per") == "cell":
        L.append(f"- **Streaming:** {b['cells']:,} cells of {b['cell_m']:,} m (loading range {b['loading_range_m']:,} m) · per cell: blockout ≤ {fmt(b['blockout_tris'])} tris, "
                 f"memory ≤ {b['memory_mb']} MB, ≤ {b['draw_calls']} draw calls, ≤ {b['shadow_lights']} shadow-casting lights")
    else:
        L.append(f"- **Budget:** blockout ≤ {fmt(b['blockout_tris'])} tris · memory ≤ {b['memory_mb']} MB · ≤ {fmt(b['draw_calls'])} draw calls · ≤ {b['shadow_lights']} shadow-casting lights")
    if e["kits"]:
        L.append("- **Kits:** " + ", ".join(kit_anchor(k) for k in e["kits"]))
    if e["markers"]:
        L.append("- **Required markers:** " + ", ".join(f"`{m}`" for m in e["markers"]))
    if e["type"] != "Planet":
        gen = ["root `LVL_` empty", "`VOL_Room_*` volume + `BLK_*_Floor` per space", "`DOOR_*` per connection"]
        if e["terrain"] or e["type"] in ("Open Region", "Planet Region"):
            gen.append("`TER_` terrain patch" + (" with authored features" if e["terrain"] else ""))
        if b.get("per") == "cell":
            gen.append("`REF_StreamingGrid`")
        if e.get("on_planet") and e["type"] in ("Open Region", "Planet Region"):
            gen.append("`REF_Curvature` (true planet surface under the flat region)")
        L.append("- **Scaffold creates:** " + ", ".join(gen) + ", `REF_Human_1p8m`, level bounds")
    if e["notes"]:
        L.append(f"- **Notes:** {esc(e['notes'])}")
    L.append("")
    return "\n".join(L)


INTROS = {
    "PLN": None,
    "KVL": "The starter region: a 64 km² open desert valley on the 120 km Earth, with ten districts placed on its map. Everything here is open from the end of the prologue; Bloom threat, not walls, gates the districts.",
    "KES": "The hand-built mission spaces of Act I, streamed as level instances inside their Kestrel Valley districts. Detailed beat flows for the flagship missions are in game bible chapter 18.",
    "ORB": "Act II's open frontier: orbit above the 120 km Earth, the Haven-9 hub, the 40 km Moon's near side, Tycho and the Styx Wreck.",
    "DRF": "The Act III anchor levels, placed on voxel planets and in space among the ~60 procedural Drift systems.",
    "SEE": "Act IV inside the 30 km living Seedship. A clearly marked point of no return precedes it.",
    "PRC": "Templates the generator fills: points of interest, Wonders, Earth Returns regions and the rules for player base zones.",
}


def group_doc(code, levels, by_id, extra_top=""):
    title, doc = GROUPS[code]
    number = doc.split("-", 1)[0]
    ls = [e for e in levels if e["group"] == code]
    L = [GENERATED_NOTE, f"# {number} — {title}", ""]
    if extra_top:
        L += [extra_top, ""]
    else:
        L += [INTROS[code], ""]
    L += [f"**{len(ls)} levels.** Standards: [00 — Level Design & Blender Standards](00-level-design-standards.md) · metrics: [02](02-metrics-and-gym.md) · kits: [10](10-modular-kits.md).", ""]
    img = OUT / "images" / f"{GROUPS[code][1][3:-3]}.jpg"
    if img.exists():
        L += [f"![{title}](images/{img.name})", ""]
    L += ["## Contents", "", "| ID | Level | Type | Act | Size |", "|---|---|---|---|---|"]
    for e in ls:
        anchor = re.sub(r"[^a-z0-9 -]", "", f"{e['id']} · {e['name']}".lower()).replace(" ", "-")
        L.append(f"| {e['id']} | [{esc(e['name'])}](#{anchor}) | {e['type']} | {esc(e['act'])} | {size_label(e['size'])} |")
    L += ["", "---", ""]
    for e in ls:
        L += [card(e, by_id), "---", ""]
    return "\n".join(L)


def planets_intro(levels):
    std = PLANET_STANDARD
    L = ["Every planet in EXODUS PROTOCOL is a **voxel planet at traversal scale: 20–120 km in diameter**, starting with the starter planet, a 120 km gameplay-scale Earth. "
         "At this scale a planet is huge on foot or by rover and has a crust deep enough for extensive voxel mining, without thousands of kilometres of empty terrain. "
         "Curvature is visible from orbit, but the surface feels flat when you're standing on it.", "",
         "![Planet scale lineup](images/planet-scale.jpg)" if (OUT / "images" / "planet-scale.jpg").exists() else "", "",
         "## The voxel planet standard", "", "| Rule | Value |", "|---|---|",
         f"| Diameter | {std['diameter_km'][0]}–{std['diameter_km'][1]} km (Earth is the maximum) |",
         "| Construction | Cube-sphere: six cube-face heightmaps plus biome, ore and Bloom maps drive voxel generation; hand-authored regions are stamped on top |",
         f"| Voxel resolution | {std['voxel_size_m']} m voxels in {std['voxel_chunk_m']} m chunks, {std['clipmap_lod_rings']} clipmap LOD rings |",
         f"| Terrain elevation | ±{int(std['max_elevation_frac'] * 1000) / 10}% of radius |",
         f"| Minable crust | {int(std['crust_depth_frac'] * 1000) / 10}% of radius, then unminable bedrock |",
         f"| Atmosphere height | {int(std['atmosphere_height_frac'] * 100)}% of radius (atmospheric thrusters fade to zero at the top) |",
         f"| Gravity | Gameplay value per planet (0.1–1.8 g). Full strength up to the tallest terrain, then falls off as (R/r)^{std['gravity_falloff_exponent']}; zero beyond {std['gravity_zero_frac']:.0f} R |",
         f"| Hand-authored regions | Built flat in a local east-north-up frame, up to {std['region_max_km']} × {std['region_max_km']} km and no more than {int(std['region_max_frac_of_diameter'] * 100)}% of the planet's diameter, then stamped onto the cube-face heightmaps (the stamp absorbs the curvature drop) |",
         "| Cube-face heightmaps | 2,048² (20 km) · 4,096² (40 km) · 8,192² (80–120 km), 16-bit |", "",
         "## Why curvature matters to level design", "",
         "On a small planet the horizon is close. Landmarks must be tall enough to clear it, or navigation breaks. Required landmark height = (distance − horizon)² / (2 × radius).", "",
         "| Diameter | Horizon at 1.8 m | Landmark height to be seen from 500 m | 1 km | 2 km | 5 km | Drop over 8 km |", "|---|---|---|---|---|---|---|"]
    for d in (20, 40, 60, 80, 100, 120):
        n = planet_numbers(d)
        cells = [fmt_m(n["horizon_m"])] + [("ground" if v < 0.5 else fmt_m(v)) for v in (n["landmark_500m"], n["landmark_1km"], n["landmark_2km"], n["landmark_5km"])]
        L.append(f"| {d} km | " + " | ".join(cells) + f" | {n['drop_8km']:.0f} m |")
    L += ["", "**Rules that follow:**",
          "1. Every district's primary landmark must be tall enough to be seen from 2 km on its planet (Earth: 20 m or more; the Moon: 75 m or more).",
          "2. Place landmarks on high ground: every 10 m of elevation adds about as much reach as 10 m of height.",
          "3. Flat regions are capped at 16 km on a side and at a quarter of the planet's diameter (10 km on the Moon, 5 km on a 20 km planet), so stamping error stays small; bigger areas are split into several stamps.",
          "4. Author the horizon: hills and mesas should hide the close geometric horizon so the world feels bigger than it is.", "",
          "## Solar-system scale", "", "| Route | Distance | Travel |", "|---|---|---|"]
    L += [f"| {a} | {b} | {c} |" for a, b, c in SYSTEM_SCALE]
    L += ["", "## Other bodies", "", "| Body | Type | Size | Notes |", "|---|---|---|---|"]
    L += [f"| {a} | {b} | {c} | {d} |" for a, b, c, d in OTHER_BODIES]
    L += ["", "## Planet summary", "", "| ID | Planet | Diameter | Gravity | Atmosphere | Crust | Horizon | Landmark for 2 km | Equator by rover |", "|---|---|---|---|---|---|---|---|---|"]
    for e in (x for x in levels if x["group"] == "PLN"):
        n, p = e["planet_numbers"], e["planet"]
        L.append(f"| {e['id']} | {e['name']} | {p['diameter_km']} km | {p['gravity_g']} g | {esc(p['atmosphere'])} | {fmt_m(n['crust_depth_m'])} | {fmt_m(n['horizon_m'])} | {fmt_m(n['landmark_2km'])} | {fmt_dur(n['rover_equator_s'])} |")
    return "\n".join(L)


def overview_doc(levels):
    L = [GENERATED_NOTE, "# 01 — Level Overview", "",
         f"Every level in EXODUS PROTOCOL: **{len(levels)} levels** across planets, open regions, districts, mission spaces, hubs, dungeons, space arenas and procedural templates.", ""]
    for img, cap in (("kestrel-valley-map.jpg", "Kestrel Valley district map, generated by the Blender level toolkit from the catalog (8 × 8 km; 256 m streaming grid)."),
                     ("planet-scale.jpg", "Planets at voxel-traversal scale (20–120 km), generated by the toolkit.")):
        if (OUT / "images" / img).exists():
            L += [f"![{cap}](images/{img})", "", f"*{cap}*", ""]
    L += ["## Level types & budgets", "", "| Type | Streaming | Blockout tris | Memory | Draw calls | Shadow lights |", "|---|---|---|---|---|---|"]
    for name, t in TYPES.items():
        stream = f"{t['cell_m']:,} m cells, {t['loading_range_m']:,} m range" if t.get("per") == "cell" else ("Voxel clipmap" if name == "Planet" else "Level instance")
        per = " per cell" if t.get("per") == "cell" else ""
        L.append(f"| **{name}** | {stream} | {fmt(t['blockout_tris'])}{per} | {t['memory_mb']} MB{per} | {fmt(t['draw_calls'])}{per} | {t['shadow_lights']} |")
    L.append("")
    for code, (title, doc) in GROUPS.items():
        ls = [e for e in levels if e["group"] == code]
        L += [f"## {code} — {title}", "", f"Chapter: [{doc}]({doc})", "", "| ID | Level | Type | Act | Missions | Size |", "|---|---|---|---|---|---|"]
        for e in ls:
            L.append(f"| {e['id']} | **{esc(e['name'])}** | {e['type']} | {esc(e['act'])} | {esc(', '.join(e['missions'])) or '—'} | {size_label(e['size'])} |")
        L.append("")
    missions = []
    for e in levels:
        for m in e["missions"]:
            missions.append((m, e["id"], e["name"]))
    L += ["## Mission → level index", "", "| Mission | Level |", "|---|---|"]
    for m, i, n in sorted(missions, key=lambda x: (x[0].replace("Cold Open", "M0.00"))):
        L.append(f"| {esc(m)} | {i} {esc(n)} |")
    L.append("")
    return "\n".join(L)


def metrics_doc():
    L = [GENERATED_NOTE, "# 02 — Metrics & the Metrics Gym", "",
         "The numbers every space is built around. They're consistent with the game bible (21 — 3Cs, 22 — Balance) and the parts bible's building grid "
         "(2.5 m large-grid cell), so authored spaces and player-built bases fit together.", ""]
    img = OUT / "images" / "metrics-gym.jpg"
    if img.exists():
        L += ["![Metrics Gym generated by the Blender level toolkit](images/metrics-gym.jpg)", "", "*The Metrics Gym, generated by `exodus_levels.py gym` from the tables below.*", ""]
    cat = None
    for c, name, val, note in METRICS:
        if c != cat:
            L += ["", f"## {c}", "", "| Metric | Value | Notes |", "|---|---|---|"]
            cat = c
        L.append(f"| {name} | **{esc(val)}** | {esc(note)} |")
    L += ["", "## Navigation agents", "", "| Agent | Radius | Height | Max step | Max slope | Used by |", "|---|---|---|---|---|---|"]
    for a in NAV_AGENTS:
        L.append(f"| **{a[0]}** | {a[1]} m | {a[2]} m | {a[3]} m | {a[4]}° | {a[5]} |")
    L += ["", "Every level bakes navmeshes for the agents that can reach it; doors, ducts and bridges are sized so the intended agents fit and the excluded ones don't (Brutes can't use 1.2 m doors; Crawlers can use ducts).", "",
          "## The Metrics Gym", "", "A generated test level (`assets/levels/gym/LVL_MetricsGym.blend`) with one lane per test. Every new movement or AI feature is checked here first.", "",
          "| Lane | Tests |", "|---|---|"]
    for lane, items in GYM:
        L.append(f"| **{lane}** | " + ", ".join(i[0] for i in items) + " |")
    L += ["", "Run `blender -b -P tools/blender/exodus_levels.py -- gym` to (re)generate it.", ""]
    return "\n".join(L)


def travel_doc(levels):
    F, P, J = FLIGHT, PULSE, JUMP
    L = [GENERATED_NOTE, "# 11 — Space Travel & Planet Transitions", "",
         "Travel works like **No Man's Sky**: one continuous universe with no loading screens. Take off from the surface, climb out of the atmosphere, "
         "pulse across the system, drop out at a planet, burn through its atmosphere and land, then step out and walk. Every transition is a short, "
         "spectacular sequence that also hides streaming. Unlike NMS, your ship is something you built, so its thrust, mass and gyroscopes shape how it flies.", "",
         "## Principles", "",
         "1. **Seamless.** Surface ↔ orbit ↔ system ↔ system without a loading screen. Loads hide inside the launch, entry, pulse and jump sequences.",
         "2. **Assisted by default.** Arcade-friendly flight with auto-levelling, terrain clearance, one-button launch and landing, and no orbital mechanics to master.",
         "3. **Your build still matters.** Thrust sets acceleration and top speed (within the caps below), gyroscopes set turn rate, mass sets inertia, and a ship can't launch "
         f"without enough thrust (auto-launch needs thrust-to-weight ≥ {F['launch_min_twr']} in local gravity).",
         "4. **Spectacle at every threshold.** Atmosphere entry, cloud punch-through, the sky fading to stars, pulse streaks, the jump tunnel.",
         "5. **Newtonian mode for purists.** A settings toggle switches to full Space Engineers-style physics (inertial dampeners, real gravity falloff, no speed caps).", "",
         "## Flight speeds (assisted mode)", "", "| Regime | Cruise | Boost | Notes |", "|---|---|---|---|",
         f"| Atmospheric flight | {F['atmo_cruise_mps'][0]}–{F['atmo_cruise_mps'][1]} m/s | {F['atmo_boost_mps']} m/s | Holds ≥ {F['min_terrain_clearance_m']} m terrain clearance unless landing |",
         f"| Airless approach (below the approach altitude) | up to {F['airless_approach_cap_mps']} m/s | — | Retro-burn VFX; lets voxel streaming keep up |",
         f"| Space (impulse) | up to {F['space_cruise_mps']:,} m/s | {F['space_boost_mps']:,} m/s | Scaled by the ship's thrust-to-mass |",
         f"| Pulse drive | spools {P['spool_s']} s, reaches {P['max_mps'] // 1000} km/s in {P['accel_s']} s | — | Blocked below {P['min_altitude_frac']} R altitude; drops out automatically |",
         f"| Jump (system to system) | {J['charge_s']} s charge + {J['tunnel_s'][0]}–{J['tunnel_s'][1]} s tunnel | — | Arrives {J['arrival']}; {J['cooldown_s'] // 60} min cooldown |", "",
         "## The journey, step by step", "",
         "```",
         f"LANDED ─[hold Launch]→ LIFT-OFF ({F['launch_lift_m']} m in {F['launch_s']} s) → ATMOSPHERIC FLIGHT ({F['atmo_cruise_mps'][1]} m/s, terrain clearance)",
         f"   → CLIMB → ATMOSPHERE EXIT (sky fades to black, stars pop in, {F['exit_sequence_s']} s) → SPACE ({F['space_cruise_mps']:,} m/s)",
         f"   → PULSE (spool {P['spool_s']} s, up to {P['max_mps'] // 1000} km/s; encounters may interrupt) → AUTO DROPOUT at the target's pulse altitude",
         f"   → APPROACH → ATMOSPHERE ENTRY (heat streaks, shake, speed capped over {F['entry_speed_ramp_s']} s; {F['entry_sequence_s']} s sequence) → CLOUD PUNCH-THROUGH",
         f"   → ATMOSPHERIC FLIGHT → LANDING PROMPT below {F['landing_prompt_altitude_m']} m over ground ≤ {F['landing_max_slope_deg']}° or a pad → AUTO-LAND ({F['auto_land_s']} s) → STEP OUT",
         "```", "",
         "| Step | What the player sees | What the engine does meanwhile |", "|---|---|---|",
         "| **Launch** | Thrusters roar, dust kicks up, the ship lifts and levels | Physics grid switches from landed (static) to flying; checks thrust-to-weight |",
         "| **Atmosphere exit** | Sky darkens, stars appear, wind noise drops away | Unloads high-detail voxel rings behind the ship; loads the system view |",
         "| **Pulse** | Streaks, the target planet swelling ahead, ETA on the HUD | Pre-streams the target planet's coarse clipmap and nearby points of interest |",
         "| **Dropout** | A thump; the planet fills the canopy | Floating-origin rebase; encounter roll resolved |",
         "| **Atmosphere entry** | Heat plasma, shaking canopy, glow, then clouds | Streams full-resolution voxels around the predicted landing area within the entry sequence |",
         "| **Landing** | Gear down, the ship settles on a pad or flat ground | Ship grid becomes static; no-build and landing-zone volumes checked |",
         "| **Jump** | The galaxy-map target locks, the ship charges, a glyph-lit tunnel | Unloads the old system, loads the new one (masked by the tunnel) |", "",
         "## Per-planet thresholds", "", "| Planet | Diameter | Pulse dropout | Atmosphere entry / approach | Cloud deck | Streaming starts | Capital parking | Dropout → landed |", "|---|---|---|---|---|---|---|---|"]
    for e in (x for x in levels if x["group"] == "PLN"):
        tn = e["transition_numbers"]
        L.append(f"| {e['name']} | {e['planet']['diameter_km']} km | {fmt_m(tn['pulse_dropout_m'])} | {fmt_m(tn['approach_altitude_m'])}{' (airless cap)' if tn['airless'] else ''} | "
                 f"{'—' if tn['airless'] else fmt_m(tn['cloud_deck_m'])} | {fmt_m(tn['streaming_start_m'])} from centre | {fmt_m(tn['capital_parking_m'])} | {fmt_dur(tn['orbit_to_ground_s'])} |")
    L += ["", "Thresholds are fractions of each planet's radius: pulse dropout at 0.5 R altitude, atmosphere top at 0.15 R, clouds at 40% of the atmosphere, streaming from 6 R.", "",
          "## Ships by size", "", "| Ship | Lands on planets? | Travel | Notes |", "|---|---|---|---|",
          "| Small grid (landers, fighters, shuttles) | Yes: auto-land on flat ground or pads | Atmosphere, space, pulse | Needs landing gear or legs for auto-land |",
          "| Medium (large-grid utility ships) | Yes, on pads ≥ 30 m or flat ground ≥ 40 m | All, including pulse | Needs a Guidance Computer for auto-land |",
          "| Capital ships (the Second Chance and larger) | **No**: park in orbit, like NMS freighters | Pulse and jump | Summon to the current system through the Jump Core; shuttle down in a small craft, or use a Beacon Relay |", "",
          "## Stations & docking", "", "| Bay | Size | Use |", "|---|---|---|"]
    L += [f"| {a} | {b} | {c} |" for a, b, c in STATIONS]
    L += ["", "Every Drift system has at least one dockable station (a Hauler waystation, a Directorate outpost or a Sower relay). Entering a bay's approach cone below 100 m/s triggers auto-dock.", "",
          "## Encounters in transit", "",
          f"- Pulse travel rolls for an interruption about {int(P['encounter_chance_per_min'] * 100)}% of the time per minute: Directorate patrols in their territory, Hauler raiders, spore-swarms near Bloomed systems, derelict distress calls.",
          "- An interruption drops the ship into a combat bubble; the pulse drive re-spools once it's clear or the player escapes the bubble (5 km).",
          "- Story beats never interrupt the player mid-pulse (game bible 08 §8.7).", "",
          "## Level design rules for travel", "",
          "1. **Readable from orbit.** Every anchor needs a landmark visible from its planet's pulse-dropout altitude (a glow, beacon or megastructure), and a waypoint label once scanned.",
          "2. **Land close to the action.** A `VOL_LandingZone` (a flat area ≥ 40 m or a pad) within 300 m of every anchor entrance; interiors that forbid ships use `VOL_NoFly`.",
          "3. **Station bays use the metrics above**; scripted approaches (Haven-9 docking in M2.01, the Seedship breach in M4.01) are drawn as `SPL_Approach_*` splines.",
          "4. **No hard ceilings.** The atmosphere top is a soft transition, never a wall; the only no-fly zones are story interiors and the Seedship.",
          "5. **Entry sequences are budgets.** Entry and jump sequences must cover the streaming they hide: designers never place a landing zone where the full-detail voxel radius (2 km) can't stream within the 8 s entry.", "",
          "## Controls (same as game bible 21 §21.3, Ship flight)", "", "| Action | KB/M | Controller |", "|---|---|---|",
          "| Launch (when landed) | Space (hold) | A (hold) |", "| Land (at the prompt) | F (hold) | X (hold) |", "| Boost | Left Alt (hold) | L3 |",
          "| Pulse drive (in space) | J (hold) | Hold Menu + A |", "| Galaxy map | M | View |",
          "| Sower jump | M, select a system, hold J | View, select, hold A |",
          "| Flight assist ↔ Newtonian (per ship) | Z (hold) | B (hold) |", "| Summon capital ship | Wrist pad → Fleet | Wrist pad → Fleet |", "",
          "## Blender spec", "",
          "- Planet scaffolds (chapter 03) add transition shells: `REF_PulseDropout`, `REF_Atmosphere` (entry), `REF_CloudDeck`, `REF_StreamingStart` and `REF_CapitalParking`, so designers see every threshold at true scale.",
          "- Levels mark travel with `VOL_LandingZone_*`, `VOL_DockingBay_*`, `VOL_NoFly_*` and `SPL_Approach_*`; all are exported to the `.markers.json` sidecar.", ""]
    return "\n".join(L)


def kits_doc():
    L = [GENERATED_NOTE, "# 10 — Modular Environment Kits", "",
         "Kits snap to a **0.5 m grid with 2.5 m modules**, so player-built blocks (parts bible, 2.5 m large-grid cells) sit flush against authored spaces. "
         "Pivot rules: **corner** = bottom-left-back corner; **bottom-center** = centre of the footprint on the floor; **center** = volume centre. "
         "Kit libraries are generated with `exodus_levels.py kit --kit KIT-XXX` (one .blend per kit, every piece blocked out at size with its pivot).", ""]
    L += ["| Kit | Art set | Pieces | Used for |", "|---|---|---|---|"]
    for k in KITS:
        L.append(f"| **{k['code']} — {k['name']}** | {k['art']} | {len(k['pieces'])} | {k['use']} |")
    L.append("")
    for k in KITS:
        L += [f"## {k['code']} — {k['name']}", "", f"**Art set:** {k['art']} (parts bible 19) · **Used for:** {k['use']} · **File:** `assets/levels/kits/{k['code'].replace('-', '_')}_{pascal(k['name'])}.blend`", "",
              "| Piece | Asset | Size (W × D × H) | Pivot | LOD0 tris | Notes |", "|---|---|---|---|---|---|"]
        for p in k["pieces"]:
            L.append(f"| {p['name']} | `SM_{k['code'].replace('-', '_')}_{pascal(p['name'])}` | {' × '.join(f'{v:g} m' for v in p['size'])} | {p['pivot']} | {fmt(p['tris'])} | {esc(p['notes']) or '—'} |")
        L.append("")
    L += ["## Kit rules", "",
          "1. Every piece's footprint is a multiple of 0.5 m; wall lengths are multiples of 2.5 m.",
          "2. Walls are 0.3 m thick (industrial) or 0.25 m (domestic); floors 0.2 m; ceilings 0.3 m, so a 2.5 m storey plus slab reads as 3.0 m.",
          "3. Doorways match the parts bible door sizes (1.2 × 2.2 m and 2.4 × 2.2 m).",
          "4. LOD chain as parts bible 00 (50/20/6%); collision ≤ 4 convex hulls per piece.",
          "5. Trim-sheet texturing (parts bible 19) so kits accept faction skins.", ""]
    return "\n".join(L)


# --------------------------------------------------------------------------- data
def write_data(levels):
    DATA.mkdir(parents=True, exist_ok=True)
    payload = OrderedDict(schema="exodus.levels/1", planet_standard=PLANET_STANDARD, types=TYPES, groups={k: {"title": v[0], "doc": v[1]} for k, v in GROUPS.items()},
                          marker_prefixes=MARKER_PREFIXES, metrics=[dict(zip(["category", "metric", "value", "notes"], m)) for m in METRICS],
                          nav_agents=[dict(zip(["name", "radius", "height", "step", "slope", "used_by"], a)) for a in NAV_AGENTS],
                          gym=[{"lane": lane, "items": [{"label": i[0], "kind": i[1], "param": i[2]} for i in items]} for lane, items in GYM],
                          kits=KITS, levels=levels, other_bodies=OTHER_BODIES, system_scale=SYSTEM_SCALE,
                          travel={"flight": FLIGHT, "pulse": PULSE, "jump": JUMP, "thresholds": THRESHOLDS, "stations": STATIONS})
    (DATA / "levels.json").write_text(json.dumps(payload, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    with open(DATA / "level_tracker.csv", "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["asset", "level_id", "name", "group", "type", "act", "missions", "size_m_WxDxH", "spaces", "kits", "required_markers",
                    "blockout_tris_budget", "budget_per", "memory_mb", "blend_path", "status", "owner", "notes"])
        for e in levels:
            s = e["size"]
            w.writerow([e["asset"], e["id"], e["name"], e["group"], e["type"], e["act"], "; ".join(e["missions"]), f"{s['w']}x{s['d']}x{s['h']}",
                        len(e["spaces"]), " ".join(e["kits"]), " ".join(e["markers"]), e["budget"]["blockout_tris"], e["budget"].get("per", "level"),
                        e["budget"]["memory_mb"], e["blend_path"], "Not started", "", e["notes"]])
    with open(DATA / "kit_tracker.csv", "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["asset", "kit", "piece", "size_m_WxDxH", "pivot", "lod0_tris", "art_set", "status", "owner", "notes"])
        for k in KITS:
            for p in k["pieces"]:
                w.writerow([f"SM_{k['code'].replace('-', '_')}_{pascal(p['name'])}", k["code"], p["name"], "x".join(f"{v:g}" for v in p["size"]),
                            p["pivot"], p["tris"], k["art"], "Not started", "", p["notes"]])


def update_readme(levels):
    readme = OUT / "README.md"
    if not readme.exists():
        return
    text = readme.read_text(encoding="utf-8")
    a, b = "<!-- STATS:START -->", "<!-- STATS:END -->"
    if a not in text:
        return
    rows = [a, "| | Count |", "|---|---|"]
    for code, (title, _d) in GROUPS.items():
        rows.append(f"| {title} | {sum(1 for e in levels if e['group'] == code)} |")
    rows += [f"| **Levels total** | **{len(levels)}** |", f"| Modular kits | {len(KITS)} kits · {sum(len(k['pieces']) for k in KITS)} pieces |",
             f"| Metrics | {len(METRICS)} metrics · {len(NAV_AGENTS)} navigation agents · {len(GYM)} gym lanes |", b]
    readme.write_text(text[: text.index(a)] + "\n".join(rows) + text[text.index(b) + len(b):], encoding="utf-8")


def main():
    levels, problems = expand()
    if problems:
        print("\n".join(problems))
        sys.exit(1)
    if "--check" in sys.argv:
        print(f"OK: {len(levels)} levels, {len(KITS)} kits")
        return
    by_id = {e["id"]: e for e in levels}
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "01-level-overview.md").write_text(overview_doc(levels) + "\n", encoding="utf-8")
    (OUT / "02-metrics-and-gym.md").write_text(metrics_doc() + "\n", encoding="utf-8")
    for code in GROUPS:
        extra = planets_intro(levels) if code == "PLN" else ""
        (OUT / GROUPS[code][1]).write_text(group_doc(code, levels, by_id, extra) + "\n", encoding="utf-8")
    (OUT / "10-modular-kits.md").write_text(kits_doc() + "\n", encoding="utf-8")
    (OUT / "11-space-travel-and-planet-transitions.md").write_text(travel_doc(levels) + "\n", encoding="utf-8")
    write_data(levels)
    update_readme(levels)
    print(f"Built {len(levels)} levels, {len(KITS)} kits ({sum(len(k['pieces']) for k in KITS)} pieces) -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
